Bugfix/128 None and Unknown Actors
Studio-Lovelies/GG-JointJustice-Unity pull request #136
Opened 2021-12-31 00:20 UTC by notexplosive

## Summary
This PR adds two new commands (that need to be added to the Wiki just before this PR goes through). Technically this is a bug fix because these things worked before. But now they work again (maybe) even better-er than before!

- `&SPEAK_UNKNOWN:<actorName>` which is similar to `&SPEAK:<actorName>` except the name is obscured as `???`, but we keep the NameBox color (see gif)

- `&NARRATE` which is equivalent to `&SPEAK:None` this disables the NameBox, typically used for narration.

## Before/after screenshots and/or animated gif

![unknown-name-2](https://user-images.githubusercontent.com/6920005/147795936-ceac783a-2eda-4fb5-8996-ea95686e1f86.gif)

## Testing instructions
I modified `AppearingDialogInk` to test out my changes. But feel free to write up your own ink using `&SPEAK_UNKNOWN` and &NARRATE`

## Additional information

- `[kinda]` Changes UI
- `[kinda]` Introduces new feature
- `[ ]` Removes existing feature
- `[x]` Has associated resource: 
#128

2021-12-31 02:01 UTC, PhoebeMitchell approved these changes, later dismissed
Two PRs in one night! Smashing it! 👯‍♀️

2021-12-31 02:01 UTC, PhoebeMitchell commented on Assets/Resources/InkDialogueScripts/AppearingDialogInk.ink
> +&NARRATE
Could you move this file and the JSON file to the TestScripts folder? I know all the other scripts aren't in there yet, but may as well make a start.

2021-12-31 02:01 UTC, PhoebeMitchell commented on Assets/Scripts/Actor/ActorController.cs
> +        _onNarrate += _nameBox.SetSpeakerToNarrator;
What's the reasoning behind making these events? Could they not be called directly when needed?

2021-12-31 02:01 UTC, PhoebeMitchell commented on Assets/Scripts/UI/NameBox.cs
> +        _text.text = nameToDisplay;
Could this be done with a conditional operator? (_text.text = speakingType == SpeakingType.SpeakingWithUnknownName ? ...)

2021-12-31 02:01 UTC, PhoebeMitchell commented on Assets/Scripts/UI/NameBox.cs
>          gameObject.SetActive(actorData.DisplayName != "");
Maybe replace this with just SetActive(true) now

2021-12-31 02:01 UTC, PhoebeMitchell commented on Assets/Scripts/Actor/ActorController.cs
> +            }
This could be moved to its own method which is called by ActionDecoder. This would save having to deal with passing NarratorActorName back and forth. Unless the idea was to keep &SPEAK:None as a valid action? Personally I think it should be one or the other.

2021-12-31 15:18 UTC, ViMaSter submitted a review, later dismissed
Added votes and comments to already existing threads, but nothing worth blocking from my end either, well done! 👍

2021-12-31 15:18 UTC, ViMaSter commented on Assets/Scripts/Actor/ActorController.cs
> +            }
The more I think about it, I actually find myself agreeing with moths proposal here of **either** using `&SPEAK:None` **or** having a `&NARRATE`, but not supporting both.  

Instead of hardcoding an actor name for the narrator, could we introduce a third `SpeakingType` for the narrator instead?  
This would also remove the need to [expose `NarratorActorName` inside the `IActorController`-interface](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/pull/136/files#diff-441524bcf9bcee899df034a0b01c2398f6492bce70e53bf3ab8159930ffcb5cdR20), which feels more like an implementation detail to me, which other classes shouldn't be concerned about, as they could simply react to set `SpeakingType` instead.

2021-12-31 15:18 UTC, ViMaSter commented on Assets/Scripts/UI/NameBox.cs
> +        _text.text = nameToDisplay;
I personally try to avoid conditional operators. Similarly to early-returns, I usually find having a default and overriding it only in certain scenarios (as done here) to be more readable.  
That way, if we do want to introduce another special case later on, we'd just have to add another `if() { return; }` block, instead of expanding the conditional operator (which, when not done automatically can unintentionally introduce bugs).

2021-12-31 19:50 UTC, notexplosive commented on Assets/Scripts/UI/NameBox.cs
> +        _text.text = nameToDisplay;
Leaving this as-is. Although I like ternary it feels too cumbersome here (maybe because the names are too long?)

2021-12-31 20:13 UTC, ViMaSter submitted a review, later dismissed
One "unused property"-nit (there's always one : D), aside from that it looks pretty solid now! 👍

2021-12-31 20:13 UTC, ViMaSter commented on Assets/Scripts/Actor/ActorController.cs
> +    public string NarratorActorName { get; } = "None";
Nit: With the latest changes this is now unused and could be removed.

2022-01-01 23:35 UTC, PhoebeMitchell approved these changes, later dismissed

2022-01-02 11:41 UTC, ViMaSter submitted a review, later dismissed
Re-approving after the `develop` integration merge.

2022-01-02 15:27 UTC, PhoebeMitchell submitted a review, later dismissed

2022-01-02 15:34 UTC, PhoebeMitchell commented on Assets/Scripts/UI/NameBox.cs
> +    }
This method doesn't set the CurrentActor property. If NARRATE is called before SPEAK then no text sound will play. If NARRATE is called after SPEAK then the sound of the previous text sound will play. Maybe replace the current actor property with a GetActorSound method which returns either the actors chirp sound, or a default sound?

2022-01-02 15:44 UTC, PhoebeMitchell reviewed
Another bug, TextBoxCanBeHidden test fails on AppearingDialogueControllerTests. This is because the narrative script in Inky-TestScene disables the NameBox so it can't be found.
HOWEVER this test is supposed to test if the speech panel is disabled, not the name box. So probably should change the Find method to find the SpeechPanel object instead.

2022-01-03 15:51 UTC, notexplosive commented on Assets/Scripts/UI/NameBox.cs
> +    }
Thanks! looking at this now

FYI- Fixed the broken test mentioned in your below comment (github won't let me reply to that comment so I'm writing it here)

2022-01-03 15:55 UTC, notexplosive commented on Assets/Scripts/UI/NameBox.cs
> +    }
I can't repro this bug because I don't hear dialogue chirps at all-- are you testing a combination of both my PRs?

2022-01-03 16:07 UTC, notexplosive commented on Assets/Scripts/UI/NameBox.cs
> +    }
Narrator will now always use the default chirp sound. We'll probably want to change this but there's some extra design work there (how will the dialogue script define that?)

That can be part of this PR if we have an idea we like now-- or it can wait until later and I can open an issue.

2022-01-05 21:35 UTC, PhoebeMitchell requested changes
The default chirp does not play 😭

2022-01-05 21:35 UTC, PhoebeMitchell commented on Assets/Scripts/UI/AppearingDialogueController.cs
>          if (chirp == null)
Bottom if statement is never reached if currentActorChip is null

2022-01-05 21:48 UTC, PhoebeMitchell commented on Assets/Scripts/UI/NameBox.cs
> +    }
I'm happy with just having one default sound for now. We can add it in future if needed.

2022-01-06 17:08 UTC, notexplosive commented on Assets/Scripts/UI/AppearingDialogueController.cs
>          if (chirp == null)
whoops.

2022-01-07 00:49 UTC, PhoebeMitchell approved these changes
All looks good now 👍

2022-01-07 14:19 UTC, ViMaSter approved these changes
Test run, so LGTM!

2022-01-08 22:57 UTC, merged