feature/130-Speech-box-continue-arrow
Studio-Lovelies/GG-JointJustice-Unity pull request #137
Opened 2022-01-01 02:34 UTC by PhoebeMitchell

## Summary

Adds the continue arrow to the SpeechPanel prefab. Hooks it up to the correct events in StandardInclusion prefab to make it disappear and appear when text starts and ends respectively.

## Before/after screenshots and/or animated gif

![continuearrow](https://user-images.githubusercontent.com/67964179/147842840-698736bc-9cd9-48b2-a284-313252cfc47b.gif)

## Testing instructions

Open Inky-TestScene and play a script. The arrow should appear at the end of every line of text (except ones that appear instantly with the APPEAR_INSTANTLY actions)

## Additional information

- `[x]` Changes UI
- `[x]` Introduces new feature
- `[ ]` Removes existing feature
- `[ ]` Has associated resource:

2022-01-01 16:50 UTC, ViMaSter requested changes
Hm... It seems like the animation is actually broken for me. I've put a bit more info in the thread below, blocking this merge for now, until that's resolved.

2022-01-01 16:50 UTC, ViMaSter commented on Assets/Animations/UI/ContinueArror.controller
> +%YAML 1.1
Hmm... For some reason Unity flags this as an invalid Animation Controller for me and prints this instead of playing the animation: (running Windows 10, 19043)
![image](https://user-images.githubusercontent.com/1689033/147855464-a167a21e-c0c9-409a-a12b-475514438c10.png)
Wanted to check if it also happens [in the build for this PR](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/suites/4803380329/artifacts/134837133), but I'm stuck on an animating Arin sprite with no text box, if I select `New Game`.
![image](https://user-images.githubusercontent.com/1689033/147855546-0d8b9e5d-1f66-4c1d-9912-61f327fa6eb0.png)

Nit: This file is also got a typo: `ContinueArro>r<.controller`

2022-01-01 18:55 UTC, notexplosive commented on Assets/Animations/UI/ContinueArror.controller
> +%YAML 1.1
I fetched and checked out this branch and I don't see the warning message you're seeing.

2022-01-01 18:58 UTC, notexplosive commented on Assets/Animations/UI/ContinueArror.controller
> +%YAML 1.1
When I load the build I also just see Arin in a black void... but I'm not sure what the old behavior was. Investigating.

2022-01-01 19:10 UTC, notexplosive approved these changes, later dismissed
Since this change has zero .cs changes, I don't really know how to review it (my least favorite part of using Unity). But it runs correctly so I'll assume it's correct.

2022-01-01 19:58 UTC, PhoebeMitchell commented on Assets/Animations/UI/ContinueArror.controller
> +%YAML 1.1
This problem should be fixed in latest commits

2022-01-01 20:25 UTC, ViMaSter submitted a review, later dismissed
Works now, thanks for addressing that Animator issue!

---

Nit: I randomly had the `AppearingDialogInk` script active and on the "This text appears instantly" line no arrow is shown:
![image](https://user-images.githubusercontent.com/1689033/147859458-20745c03-e523-4702-b45c-fcf5d9d747ed.png)

On the line before and after that it's happily bopping though:
![SPA9boMi5E](https://user-images.githubusercontent.com/1689033/147859465-cd207b42-e24f-4663-a85e-cb3b9a1a2fff.gif)

Not worth blocking though, it's just an inconsistency. Unless it actually a bug, in which case either make a new issue or fix it and I'll re-test and approve! : D

2022-01-02 01:21 UTC, ViMaSter requested changes
Sorry for having to hand it back again; the arrow in the `Inky-TestScene` is completely gone now. : D
On 2948c85b920ddf15c4f2dca196e291ff42ca796e (the latest commit of this branch) it's gone:
![image](https://user-images.githubusercontent.com/1689033/147863623-d71477ef-4b2b-4d83-890c-4789eccdb993.png)

On 6928f799fd0e11b452a8e41c30234a212ec4ece6 (commit I tested on for my last approval):
![image](https://user-images.githubusercontent.com/1689033/147863645-ecc593aa-4b2a-4b36-ac4a-8f8583c49b4c.png)

The behavior is consistent across `AddRecordTest` and `AppearingDialogInk` in both versions.

2022-01-02 01:28 UTC, ViMaSter commented on Assets/Animations/UI/ContinueArror.controller
> +%YAML 1.1
Also [created a bug report](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/issues/143) for the main menu behavior I encountered.

2022-01-02 02:05 UTC, ViMaSter approved these changes
Seems like that last commit did it; works for me as well now! :)

2022-01-02 02:26 UTC, notexplosive approved these changes
Rocket Emoji

2022-01-02 03:24 UTC, merged