Feature/47 normalize asset names
Studio-Lovelies/GG-JointJustice-Unity pull request #141
Opened 2022-01-01 20:49 UTC by notexplosive

## Summary
All assets now have NamesLikeThis where the first letter of each word is capital.

## Before/after screenshots and/or animated gif

## Testing instructions
Pull down the branch and:
-Try to find a script/scene that's broken with these changes. Cross Exam (which feels the most complex) works on my machine
-Try to find an asset with a wrong name.

## Additional information

- `[ ]` Changes UI
- `[ ]` Introduces new feature
- `[ ]` Removes existing feature
- `[x]` Has associated resource: 
#47

2022-01-01 21:17 UTC, ViMaSter commented
Had a quick crawl with [Search Everything](https://www.voidtools.com/) (`ABSOLUTE PATH TO YOUR REPO\Assets case:regex:^[a-z]` as query if you want to run it locally) through the `/Assets`-folder after switching to that branch and found these left:

- [`Images/BackgroundsAndForegrounds/lobby.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/BackgroundsAndForegrounds/lobby.png)
- [`Images/Characters/Arin/wideshot.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/Characters/Arin/wideshot.png)
- [`Images/Characters/Jory/jorywideshot.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/Characters/Jory/jorywideshot.png)
- [`Images/Characters/JudgeBrent/brentwideshot.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/Characters/JudgeBrent/brentwideshot.png)
- [`Images/Characters/Ross/wideshot.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/Characters/Ross/wideshot.png)
- [`Images/Characters/TutorialBoy/wideshot.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/Characters/TutorialBoy/wideshot.png)
- [`Images/Evidence/attorneyBadge.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/Evidence/attorneyBadge.png)
- [`Images/Evidence/bentCoins.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/Evidence/bentCoins.png)
- [`Images/Evidence/joryBackpack.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/Evidence/joryBackpack.png)
- [`Images/Evidence/jorySrLetter.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/Evidence/jorySrLetter.png)
- [`Images/Evidence/livestreamRecording.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/Evidence/livestreamRecording.png)
- [`Images/Evidence/nintendoSwitch.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/Evidence/nintendoSwitch.png)
- [`Images/Evidence/plumberInvoice.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/Evidence/plumberInvoice.png)
- [`Images/Evidence/stolenDinos.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/Evidence/stolenDinos.png)
- [`Images/Shouts/holdIt.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/Shouts/holdIt.png)
- [`Images/Shouts/objection.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/Shouts/objection.png)
- [`Images/Shouts/takeThat.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/Shouts/takeThat.png)
- [`Images/UI/courtRecord.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/UI/courtRecord.png)
- [`Images/UI/evidence.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/UI/evidence.png)
- [`Images/UI/evidence_01.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/UI/evidence_01.png)
- [`Images/UI/explosion sheet1.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/UI/explosion%20sheet1.png)
- [`Images/UI/explosion sheet2.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/UI/explosion%20sheet2.png)
- [`Images/UI/explosion sheet3.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/UI/explosion%20sheet3.png)
- [`Images/UI/profiles.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/UI/profiles.png)
- [`Images/UI/record_icon #886.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/UI/record_icon%20%23886.png)
- [`Images/UI/record_icon #888.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/Images/UI/record_icon%20%23888.png)
- [`OldProjectFiles/Images/BackgroundsAndForegrounds/blackScreen.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/OldProjectFiles/Images/BackgroundsAndForegrounds/blackScreen.png)
- [`OldProjectFiles/Images/BackgroundsAndForegrounds/courtAssistant.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/OldProjectFiles/Images/BackgroundsAndForegrounds/courtAssistant.png)
- [`OldProjectFiles/Images/BackgroundsAndForegrounds/courtDefense.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/OldProjectFiles/Images/BackgroundsAndForegrounds/courtDefense.png)
- [`OldProjectFiles/Images/BackgroundsAndForegrounds/courtDefense2.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/OldProjectFiles/Images/BackgroundsAndForegrounds/courtDefense2.png)
- [`OldProjectFiles/Images/BackgroundsAndForegrounds/courtJudge.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/OldProjectFiles/Images/BackgroundsAndForegrounds/courtJudge.png)
- [`OldProjectFiles/Images/BackgroundsAndForegrounds/courtPan.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/OldProjectFiles/Images/BackgroundsAndForegrounds/courtPan.png)
- [`OldProjectFiles/Images/BackgroundsAndForegrounds/courtPan2.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/OldProjectFiles/Images/BackgroundsAndForegrounds/courtPan2.png)
- [`OldProjectFiles/Images/BackgroundsAndForegrounds/courtProsecution.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/OldProjectFiles/Images/BackgroundsAndForegrounds/courtProsecution.png)
- [`OldProjectFiles/Images/BackgroundsAndForegrounds/courtProsecution2.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/OldProjectFiles/Images/BackgroundsAndForegrounds/courtProsecution2.png)
- [`OldProjectFiles/Images/BackgroundsAndForegrounds/courtWitness.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/OldProjectFiles/Images/BackgroundsAndForegrounds/courtWitness.png)
- [`OldProjectFiles/Images/BackgroundsAndForegrounds/courtWitness2.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/OldProjectFiles/Images/BackgroundsAndForegrounds/courtWitness2.png)
- [`OldProjectFiles/Images/BackgroundsAndForegrounds/lobby.png`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/363bbeb2fdc1a37dad202b6312d091dbd3d1dea1/Assets/OldProjectFiles/Images/BackgroundsAndForegrounds/lobby.png)
- [`OldProjectF [...]

2022-01-02 03:10 UTC, notexplosive commented
Deliberately leaving the OldProjectFiles alone, as well as:
Resources/Story/gameover.txt
Resources/Story/part4.txt
Resources/Story/part5.txt
Resources/Story/part6.txt
Resources/Story/turnabout1_preTrial.txt
Resources/Story/turnabout1_trialPart1.txt
Resources/Story/turnabout1_trialPart2.txt
Resources/Story/turnabout1_trialPart3.txt

Because they're all .txt files and aren't going to be engaged with the same was as the others

2022-01-03 03:00 UTC, PhoebeMitchell requested changes
Nice, and with a test too. Love to see it.
Unfortunately the changes seem to have broken ActionDecoderTests and ActionDecoderEnumTests, so fix those and should be good for approval.

2022-01-03 03:00 UTC, PhoebeMitchell commented on Assets/Scripts/TextDecoder/AssetName.cs
> +    public string NormalizedName { get; set; }
nit: property should be before methods

2022-01-03 03:00 UTC, PhoebeMitchell commented on Assets/Scripts/TextDecoder/AssetName.cs
> +
nit: Unused namespaces

2022-01-03 03:00 UTC, PhoebeMitchell commented on Assets/Scripts/TextDecoder/AssetName.cs
> +            var node = firstChar + item.Substring(1, item.Length - 1);
nit: Use string interpolation

2022-01-05 21:47 UTC, PhoebeMitchell requested changes
Some tests fail: VerifyActionDecoderTrimsExcessWhitespace and the EvidenceMenu tests (because BGScene names in Inky-TestScene need to be updated).

Also the explosion animation for penalties is missing its sprites.

2022-01-07 01:22 UTC, PhoebeMitchell approved these changes, later dismissed
Everything appears to work. One comment on printing AssetNames.

2022-01-07 01:22 UTC, PhoebeMitchell commented on Assets/Scripts/BGScenes/BGSceneList.cs
> +    public BGScene SetScene(AssetName sceneName) //TODO: Change this when making file names universal
This change from string to AssetName means printing sceneName below just prints AssetName. Maybe add a ToString override for AssetName. This could replace the NormalizedName property.

2022-01-07 14:45 UTC, ViMaSter submitted a review, later dismissed
The `AssetName` class as a safe wrapper around file names is awesome! Tests all pass and seems like all files are updated too so thanks for taking care of each of those files!

2022-01-07 14:45 UTC, ViMaSter commented on Assets/Scripts/TextDecoder/AssetName.cs
> +        return this._internalString;
Nit: Unsure if we ever decided on a specific style, but my IDE marks `this.` as superfluous, as there's no parameter conflicting with that name.

2022-01-07 14:45 UTC, ViMaSter commented on Assets/Tests/EditModeTests/AssetNameTests.cs
> +using UnityEngine.TestTools;
Nit: No symbols from these namespaces are used in this file so they should be safe to remove.

2022-01-08 22:56 UTC, notexplosive commented on Assets/Scripts/TextDecoder/AssetName.cs
> +        return this._internalString;
My b. I prefer `this.` (so my editor defaults to using it and I don't want to turn that off for my personal projects) but we _did_ agre no to use `this.` so I'll change it

2022-01-08 23:09 UTC, ViMaSter approved these changes
Thanks for addressing the threads; looks good to me now!

2022-01-08 23:14 UTC, PhoebeMitchell approved these changes

2022-01-08 23:26 UTC, merged