Replaced included default player actions with custom player actions
Studio-Lovelies/GG-JointJustice-Unity pull request #155
Opened 2022-01-21 07:27 UTC by ViMaSter

## Summary
This PR removes all references in our project to the `DefaultPlayerActions` that are included as an example inside the `Input System` package and instead uses the `PlayerActions` instance at `/Assets/Scripts/Input/Control.cs` were using for the rest of the game already.

## Before/after screenshots and/or animated gif
### Unused UI input system actions
Unity's UI Input system consists of some behaviors we're currently not using. As we're not using them, I've deliberately left them unassigned:
- Middle Click
- Right Click
- Scroll Wheel
- Tracked Position and Orientation (not to be confused with the mouse position called `Point`, that's assigned; think a phone's gyro sensor or a Wiimote)

![image](https://user-images.githubusercontent.com/1689033/150483741-3c28a3c9-72ec-4a43-9909-d29cab1f6d0c.png)

### `DirectionalButtons` vs. individual `Left`, `Right`, `Up`, `Down` actions
Our `Controls` had both `DirectionalButtons` **and** individual `Left`, `Right`, `Up`, `Down` actions. I've removed the individual actions as they a) seemed unused and b) can easily be accessed by listening to changes of the `DirectionalButtons` axis.  
It now looks like this:  
![image](https://user-images.githubusercontent.com/1689033/150483754-fa82ccf5-3990-4e60-98e3-10252a5f5323.png)

### `X` and `Enter`
`X` and `Enter` can now be used interchangeably. I haven't really seen the need to separate the two, but if we want to split "Dialogue actions" and "UI actions" later on, it's something we can always do.

## Testing instructions
1. Run any scene of the game
2. Make sure all actions previously executable are still executable; aside from `X` and `Enter` now able to be used interchangeably, no keybinds should have changed
3. Verify the EditMode and PlayMode tests still succeed

## Additional information

- `[x]` Changes UI
  - `X` and `Enter` key can now be used interchangeably 
- `[ ]` Introduces new feature
- `[ ]` Removes existing feature
- `[ ]` Has associated resource:
  - Closes #139

2022-01-22 02:14 UTC, PhoebeMitchell approved these changes, later dismissed
Thanks for taking on this issue, because I really didn't wanna do it :D

2022-01-22 02:14 UTC, PhoebeMitchell commented on unity-ggjj/Assets/Scenes/Inky-TestScene.unity
> +    - target: {fileID: 6276402831480686355, guid: ba051a1745ca9df40845054bf2e42823, type: 3}
Unrelated to this line, but the input actions needs to be updated in the MainMenu scene

2022-01-22 13:58 UTC, ViMaSter commented on unity-ggjj/Assets/Scenes/Inky-TestScene.unity
> +    - target: {fileID: 6276402831480686355, guid: ba051a1745ca9df40845054bf2e42823, type: 3}
...and actually not just there, it turns out:
![image](https://user-images.githubusercontent.com/1689033/150641116-eaa6f196-b386-4d2c-a22d-ac0aaab853c1.png)
Well spotted! Shoud've done that search in the first place, so thanks for that find! Updated those scenes in https://github.com/Studio-Lovelies/GG-JointJustice-Unity/pull/155/commits/4ddc4908b44115ef7a0333b15636bf6ecf6117b9.

2022-02-01 05:36 UTC, notexplosive submitted a review, later dismissed
I don't really understand the changes (looks like Unity nonsense). But if it works it works, I'll take it!

2022-02-05 20:38 UTC, lyndsiWilliams requested changes
These tests are failing consistently:
![image](https://user-images.githubusercontent.com/55605634/152658141-83ed3694-124b-4dc7-8137-c249e4c44a94.png)

2022-02-05 22:15 UTC, ViMaSter commented
@lyndsiWilliams Hmm... I was actually able to run them locally.
![image](https://user-images.githubusercontent.com/1689033/152660624-e4f4a45e-3796-4ed9-9dcd-08ba821075b5.png)
Can you check if this is related to the virtual input device limit issue we ran into on the other branch too?

If the logs contain something along the lines of `NotSupportedException: Control count per binding cannot exeed byte.MaxValue=255` restarting the Unity Editor should fix it.

---

Also feel free to always attach the full logs any of the failed tests. If the comment is getting too big, a link to a secret gist at http://gist.github.com/ works too. : D (Just paste the full log, click `Create secret gist` from the dropdown button at the bottom right and paste the URL you land on here!)
![image](https://user-images.githubusercontent.com/1689033/152660676-28832bdb-e5a3-4559-8046-0b93eccb4f28.png)
https://gist.github.com/ViMaSter/66fa237b0f1354cf5cc271a6d2e5476e

2022-02-06 01:35 UTC, lyndsiWilliams commented
> @lyndsiWilliams Hmm... I was actually able to run them locally. ![image](https://user-images.githubusercontent.com/1689033/152660624-e4f4a45e-3796-4ed9-9dcd-08ba821075b5.png) Can you check if this is related to the virtual input device limit issue we ran into on the other branch too?
> 
> If the logs contain something along the lines of `NotSupportedException: Control count per binding cannot exeed byte.MaxValue=255` restarting the Unity Editor should fix it.
> 
> Also feel free to always attach the full logs any of the failed tests. If the comment is getting too big, a link to a secret gist at http://gist.github.com/ works too. : D (Just paste the full log, click `Create secret gist` from the dropdown button at the bottom right and paste the URL you land on here!) ![image](https://user-images.githubusercontent.com/1689033/152660676-28832bdb-e5a3-4559-8046-0b93eccb4f28.png) https://gist.github.com/ViMaSter/66fa237b0f1354cf5cc271a6d2e5476e

Very strange indeed, it doesn't seem to be the same errors that we were seeing before. Here's a gist with the errors I'm seeing on my side: https://gist.github.com/lyndsiWilliams/f0ef510635f5b4c6532611a70610cd1d

Also, I didn't know github gists were a thing, that's handy! 😮

2022-02-06 11:25 UTC, ViMaSter commented
@lyndsiWilliams Since most of the failing tests are mouse-related, are you running the tests and then focussing another window or running them in the background? Unity's Input System can fail if you run all tests in succession but the Unity Editor isn't focussed.

If that also doesn't work, I've noticed there's logs missing GameObjects and Components; can you actually run the `AppearingDialogueController - Test Scene` by hand, press `Esc` and open the menu? Or are there any errors inside the Console (`Window -> General -> Console`) when you try and do that?
![image](https://user-images.githubusercontent.com/1689033/152678492-bf41cb43-1c07-46b7-be69-630972167163.png)

2022-02-06 19:54 UTC, PhoebeMitchell approved these changes
Tests run fine on my end

2022-02-09 23:37 UTC, lyndsiWilliams approved these changes
Sorry for the holdup on this - all the tests run on my end now! Not sure what the issue was before 🤷

2022-02-10 00:35 UTC, merged