Feature/restart project files
Studio-Lovelies/GG-JointJustice-Unity pull request #16
Opened 2021-08-14 21:51 UTC by alipapapupu

## Summary

Added some files to .gitignore
Moved all old project files to OldProjectFiles-folder
Moved all unneeded folders from Resources-folder to Assets-folder
Added empty files to populate Scenes- and Scripts-folders.

## Before/after screenshots and/or animated gif

## Testing instructions

## Additional information

- `[ ]` Changes UI
- `[ ]` Introduces new feature
- `[ ]` Removes existing feature
- `[ ]` Has associated resource:

2021-08-15 17:10 UTC, TooManyMoths approved these changes
Assets/Images/Characters/Arin/Untitled-1.psd appears to be the PSD file of Assets/Images/Characters/Arin/Objection_ani.png so could be deleted along with its .meta file.

New scene could use a canvas if we are creating the game using UI.

Otherwise the project opens without errors and old project files still function.

2021-08-15 18:02 UTC, JuiceGrape approved these changes
Worked with it, works

2021-08-16 05:54 UTC, JuiceGrape requested changes
This pr is for merging into master. Please change it to merge into develop.

2021-08-16 08:23 UTC, JuiceGrape approved these changes

2021-08-16 08:24 UTC, merged