Feature/15 new dialogue decoder
Studio-Lovelies/GG-JointJustice-Unity pull request #17
Opened 2021-08-16 19:55 UTC by JuiceGrape

## Summary
New dialogue decoder style. The director action decoder is a pretty stand alone class that takes action strings input by the script and decodes them into the proper action, which it then delegates to one of (currently) four controller interfaces, which actually interact with unity. These controllers need implementation, which can be doen in paralel in future stories. It also has some basic events, but currently doesn't wait actions to complete before continuing. 

## Testing instructions
Right now, it isn't functional yet, except for the debug line which allows you to press space to continue through the example script provided in the Inky-TestScene.

## Additional information

- `[ ]` Changes UI
- [x] Introduces new feature
- `[ ]` Removes existing feature
- [x] Has associated resource: 
  
https://github.com/Studio-Lovelies/GG-JointJustice-Unity/issues/15

2021-08-16 21:34 UTC, TooManyMoths approved these changes
Comments are only minor convention discrepancies. Structure of the code makes sense and is understandable. Runs without errors.

2021-08-16 21:34 UTC, PhoebeMitchell commented on Assets/Scripts/AudioController.cs
> +    public void PlayBGSong(string Song)
camelCase for parameters. Change to song.

2021-08-16 21:34 UTC, PhoebeMitchell commented on Assets/Scripts/AudioController.cs
> +    public void PlaySFX(string SFX)
Consider changing to PlaySfx and sfx to abide by C# capitalization conventions
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions

2021-08-16 21:34 UTC, PhoebeMitchell commented on Assets/Scripts/EvidenceController.cs
> +            Debug.LogError("Evidence Controller doesn't have a action decoder to attach to");
Change "a action" to "an action"

2021-08-16 21:34 UTC, PhoebeMitchell commented on Assets/Scripts/Interfaces/IActorController.cs
> +using UnityEngine;
Unused using directives.

2021-08-16 21:34 UTC, PhoebeMitchell commented on Assets/Scripts/Interfaces/IActorController.cs
> +
Remove blank line

2021-08-16 21:34 UTC, TooManyMoths commented on Assets/Scripts/Interfaces/ISceneController.cs
> +}
Consider changing enum name and values to PascalCase to abide by C# naming conventions

2021-08-17 03:34 UTC, notexplosive commented on Assets/Scripts/AudioController.cs
> +    public void PlaySFX(string SFX)
All that talk about capitalization and we didn't discuss how we should capitalize "ID"

2021-08-17 05:02 UTC, notexplosive requested changes
Mostly variable name nitpicks. I have some thoughts about the structure of `DirectorActionDecoder.cs`, I think there's a missing abstraction but I'd have to mess with the code myself to find it. The rest of it looks good though!

2021-08-17 05:02 UTC, notexplosive commented on Assets/Scripts/SceneController.cs
> +    public void PanCamera(float seconds, int xEnd, int yEnd)
Could this just take a `Unity.Vector2Int` instead of an x,y?

2021-08-17 05:02 UTC, notexplosive commented on Assets/Scripts/TextDecoder/DialogueController.cs
> +            string curLine = _inkStory.Continue();
nit: `currentLine`, I hate abbrevs

2021-08-17 05:02 UTC, notexplosive commented on Assets/Scripts/Interfaces/ISceneController.cs
> +    void SetCameraPos(int x, int y);
Ditto here about `Vector2Int`

2021-08-17 05:02 UTC, notexplosive commented on Assets/Scripts/Interfaces/ISceneController.cs
> +public enum itemPosition
We don't specify in the styleguide but I think enum type names should be UpperCamelCase (on the same level as classes because an enum is like a class that only holds static ints)

Also consider a more informative name for this type: `HorizontalPosition`? `HorizontalAlignment`? `ItemPosition` doesn't tell me anything.

2021-08-17 05:02 UTC, notexplosive commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    void SetBGMusic(string music)
nit: `music` -> `songName`

2021-08-17 05:02 UTC, notexplosive commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +            && int.TryParse(parameters[1], out y))
(Not blocking, just thinking out loud about the structure of this class)
It seems all these functions have a pattern of:

1. `Check Has[Scene/Actor]Controller, early return if its not there`
2. `Parse string as the value(s) I actually wanted, emit an error if parse fails with a helpful error message`
3. `Tell the sceneController/actorController to do the thing I said I was gonna do`

Which smells to me like a missing abstraction. I have some thoughts on how to address that but I have a hard time expressing them in a code review comment, it would be easier if I just showed you.

I'd like your permission to do a refactoring pass on this class. As a trade, I'll write tests for this class, both for the behavior and the error reporting.

2021-08-17 05:02 UTC, notexplosive commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +            Debug.LogError("Invalid paramater " + coordinates + " for function CAMERA_SET");
It would be nice if these errors told you the line number and filename of the failure so you knew where to look.

2021-08-17 05:02 UTC, notexplosive commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    void SetBackground(string background)
nit: `backgroundSceneName`

2021-08-17 05:02 UTC, notexplosive commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    /// <param name="intensity">Max displacement of the screen as a float</param>
Maybe supply an expected range? How much is `1f` intensity? How much is `100f`? Also is intensity a function of how much the screen shakes or for how long it shakes. Or is it both?

2021-08-17 05:02 UTC, notexplosive commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    /// <param name="emotion">Emotion to display for the current actor</param>
What are the values of "emotion?" is emotion a missing enum?

2021-08-17 05:02 UTC, notexplosive commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    /// Sets the shown actor in the scene
What does it mean to "set" an actor? I read the name, got confused, read the summary, am still confused.

2021-08-17 05:02 UTC, notexplosive commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    /// Called whenever a new action is performed in the script
Does "performed" mean "executed"?

Clarifying question: If I have a syntax error will I not find out until the action is executed?

2021-08-17 05:02 UTC, notexplosive commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    private void ShowActor(string showActor)
nit: `ShowActor` -> `SetActorVisibility`

If you're using VS then `CTRL R, R` will make this easy

2021-08-17 05:02 UTC, notexplosive commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    void PanCamera(string stringParameters)
nit: `stringParameters` -> `durationAndXY`, or even better `durationCommaXCommaY` 😛

2021-08-17 05:02 UTC, notexplosive commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    void ShowItem(string stringParameters)
nit: `stringParameters` -> `ItemNameAndPosition`

2021-08-17 06:02 UTC, lyndsiWilliams requested changes
Just a couple things I noticed 😁

2021-08-17 06:02 UTC, lyndsiWilliams commented on Assets/Scenes/Inky-TestScene.unity
> +  m_ObjectHideFlags: 0
Rookie question, are these member variables? If so, they should start with just `_`, the m should be removed. [Code style doc reference](https://docs.google.com/document/d/1zN4Yx62PpyXhu1g_AhtTZSC8k9e4zqWbzQPt1Hlw9Ag/edit#heading=h.bhrnxu6997n8)

2021-08-17 06:02 UTC, lyndsiWilliams commented on Assets/Scripts/SceneController.cs
> +            Debug.LogError("Scene Controller doesn't have a action decoder to attach to");
Change "a action" to "an action".

2021-08-17 07:00 UTC, bas-mentjot commented on Assets/Scripts/Interfaces/ISceneController.cs
> +public enum itemPosition
It tells you that these are the positions an item can have. Generalizing enums is bad imo, so I'll leave it as such

2021-08-17 13:13 UTC, TooManyMoths commented on Assets/Scripts/Interfaces/ISceneController.cs
> +    void SetCameraPos(int x, int y);
If camera is set using transform.position, then Vector2Int would need to be cast to a Vector2.
Creating a new Vector2 using the arguments or passing a Vector2 would eliminate the cast.
On that topic, will camera always be set to integer positions?

2021-08-17 13:46 UTC, JuiceGrape commented on Assets/Scenes/Inky-TestScene.unity
> +  m_ObjectHideFlags: 0
This is a unity file, not a script.

2021-08-17 13:48 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    /// Called whenever a new action is performed in the script
Yeah, we don't have a lint for the script. Could be added later in a different story

2021-08-17 13:48 UTC, JuiceGrape commented on Assets/Scripts/AudioController.cs
> +    public void PlaySFX(string SFX)
Seeing as it's an abbreviation I'll stick to SFX. It's a rare case, but it looks better this way

2021-08-17 13:49 UTC, JuiceGrape commented on Assets/Scripts/SceneController.cs
> +    public void PanCamera(float seconds, int xEnd, int yEnd)
Good point, hadn't considered it.

2021-08-17 13:50 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DialogueController.cs
> +            string curLine = _inkStory.Continue();
well I <3 em
Will do though ;)

2021-08-17 13:51 UTC, JuiceGrape commented on Assets/Scripts/Interfaces/ISceneController.cs
> +    void SetCameraPos(int x, int y);
Because we are working pixel perfectly, using ints is a better idea. I can change it to floats though.

2021-08-17 13:53 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +            && int.TryParse(parameters[1], out y))
Feel free to look into abstracting this behavior, as long as it doesn't get so complicated that it adds more work to extend it than it is right now. I tried, but failed, so I went with this simple way

2021-08-17 13:54 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +            && int.TryParse(parameters[1], out y))
I do feel like there are more important things than refactoring this. Maybe work on the game before improving something functional and fine?

2021-08-17 13:54 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +            Debug.LogError("Invalid paramater " + coordinates + " for function CAMERA_SET");
Unity errors already do when you double click them in the editor

2021-08-17 13:55 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    /// <param name="intensity">Max displacement of the screen as a float</param>
Not defined as of now. Should be defined by the person who implements the screen shake. My idea was a max displacement of the screen. Could add a duration flag though.

2021-08-17 13:55 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    /// <param name="emotion">Emotion to display for the current actor</param>
They're basically animations to set the character to

2021-08-17 13:56 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    /// Sets the shown actor in the scene
The actor to be shown in the current scene (aka showing dan vs showing arin vs showing tutorialboy)

2021-08-17 13:57 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    /// Called whenever a new action is performed in the script
Also will change to executed

2021-08-17 14:11 UTC, notexplosive commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +            Debug.LogError("Invalid paramater " + coordinates + " for function CAMERA_SET");
I meant the line number in the Narrative Script. Not the line number in the csharp.

2021-08-17 14:13 UTC, notexplosive commented on Assets/Scripts/TextDecoder/DialogueController.cs
> +            string curLine = _inkStory.Continue();
thx 4 expnding ur abbrev

2021-08-17 14:58 UTC, lyndsiWilliams commented on Assets/Scenes/Inky-TestScene.unity
> +  m_ObjectHideFlags: 0
Oooo my bad. So are the `m`s automatic? That could get confusing, maybe we should revisit the `m_` naming rule?

2021-08-17 15:06 UTC, notexplosive approved these changes

2021-08-17 15:26 UTC, lyndsiWilliams approved these changes

2021-08-17 20:54 UTC, JuiceGrape commented on Assets/Scripts/AudioController.cs
> +    public void PlayBGSong(string Song)
Done

2021-08-17 20:55 UTC, JuiceGrape commented on Assets/Scripts/Interfaces/IActorController.cs
> +using UnityEngine;
Removed

2021-08-17 20:55 UTC, JuiceGrape commented on Assets/Scripts/EvidenceController.cs
> +            Debug.LogError("Evidence Controller doesn't have a action decoder to attach to");
Done

2021-08-17 20:55 UTC, JuiceGrape commented on Assets/Scripts/Interfaces/IActorController.cs
> +
Done

2021-08-17 20:57 UTC, JuiceGrape commented on Assets/Scripts/Interfaces/ISceneController.cs
> +}
Done

2021-08-17 20:57 UTC, JuiceGrape commented on Assets/Scripts/SceneController.cs
> +    public void PanCamera(float seconds, int xEnd, int yEnd)
Done

2021-08-17 20:58 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DialogueController.cs
> +            string curLine = _inkStory.Continue();
Done

2021-08-17 20:58 UTC, JuiceGrape commented on Assets/Scripts/Interfaces/ISceneController.cs
> +    void SetCameraPos(int x, int y);
Changed to vector2int, can change to floats in the future if neccessary

2021-08-17 21:01 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    void SetBGMusic(string music)
done

2021-08-17 21:02 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    /// Called whenever a new action is performed in the script
done

2021-08-17 21:06 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    void SetBackground(string background)
Fully changed, should be much more representative now

2021-08-17 21:08 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    void PanCamera(string stringParameters)
Done

2021-08-17 21:09 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    void ShowItem(string stringParameters)
Done

2021-08-17 21:10 UTC, JuiceGrape commented on Assets/Scripts/SceneController.cs
> +            Debug.LogError("Scene Controller doesn't have a action decoder to attach to");
Done

2021-08-17 21:22 UTC, merged