Feature/input system
Studio-Lovelies/GG-JointJustice-Unity pull request #18
Opened 2021-08-16 23:15 UTC by TooManyMoths

## Summary

Adds the Input System package, along with code to create an Input Actions object.
Unity's new Input System will make supporting other devices easier (gamepads/mobile), and allow controls to be configurable at runtime.

## Before/after screenshots and/or animated gif

## Testing instructions

Check scenes with event systems run as expected. Event systems may need to be updated to use the new input system.

## Additional information

- `[ ]` Changes UI
- `[x]` Introduces new feature
- `[ ]` Removes existing feature
- `[ ]` Has associated resource:

2021-08-17 05:08 UTC, notexplosive commented
How do I review this? I don't really see any code changes? I'm inclined to just say "yeah that's probably right" and hit approve.

2021-08-17 05:25 UTC, lyndsiWilliams commented
> How do I review this? I don't really see any code changes? I'm inclined to just say "yeah that's probably right" and hit approve.

I think that's fine, there won't always be something wrong. Just your stamp of "Hey I looked through this and it looks good to me" is a good review, it still shows that another pair of eyes checked the code and _didn't_ find anything 😁

2021-08-17 06:12 UTC, lyndsiWilliams requested changes
Just a code style nit 😁

2021-08-17 06:12 UTC, lyndsiWilliams commented on Assets/Scripts/Input/Controls.cs
> +        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
Member variables should start with just `_`, the m should be removed. [Code style doc reference](https://docs.google.com/document/d/1zN4Yx62PpyXhu1g_AhtTZSC8k9e4zqWbzQPt1Hlw9Ag/edit#heading=h.bhrnxu6997n8)

2021-08-17 09:52 UTC, bas-mentjot commented on Assets/Scripts/Input/Controls.cs
> +        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
This is an auto generated script, best to leave it alone

2021-08-17 12:54 UTC, TooManyMoths commented on Assets/Scripts/Input/Controls.cs
> +        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
This class is generated by Input System, so I think its best to leave it as is.

2021-08-17 13:00 UTC, TooManyMoths commented
> How do I review this? I don't really see any code changes? I'm inclined to just say "yeah that's probably right" and hit approve.

It just adds the Input System package, so pretty much just check if there are any errors.
PlayerInput is the only script I created.

2021-08-17 14:58 UTC, lyndsiWilliams commented on Assets/Scripts/Input/Controls.cs
> +        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
Oooo are the `m`s automatic? That could get confusing, maybe we should revisit the `m_` naming rule

2021-08-17 15:05 UTC, lyndsiWilliams approved these changes

2021-08-20 07:03 UTC, closed without merging

2021-08-20 07:03 UTC, TooManyMoths commented
Closed because it is now part of feature/Main-Menu