#19 - Audio Controller
Studio-Lovelies/GG-JointJustice-Unity pull request #21
Opened 2021-08-19 14:58 UTC by notexplosive

## Summary

Originally this was meant to be just the "Music Player" side of the Audio Controller, but playing sound effects was pretty trivial by comparison so I included that too.

#### Music
Music is played as a single audio source attached directly to the Controller's GameObject, when you play a new track it fades out (over 1 second), then switches track, then fades in (also over 1 second). This does not (yet) support crossfade (fade out A while fading in B). Although I could make some adjustments to get us there if the sound team wants it.

There's also a "SettingsVolume" which is currently a field on AudioController but should eventually come from some core "Settings" object. This scales the total volume tween for the fader, so the fade always takes 1 second, but the amount that it fades in that time will vary depending on the settings volume.

#### Sound Effects
Sound Effects work slightly differently, since you apparently need an AudioSource (and therefore an entire game object) to play a sound. I create a child object on AudioController for each sound effect played. However, the game objects stick around after the sound is played, and they're reused if the sound is played multiple times. 

## Before/after screenshots and/or animated gif

![AudioControllerExample](https://user-images.githubusercontent.com/6920005/130090811-e22d06a8-3151-4311-8fa8-955c0b071c98.gif)

## Testing instructions

Load up the `AudioController - Test Scene` scene and press `A` and `B` to switch between two tracks. Move the SettingsMusicVolume slider up and down while the music is playing. Try adjusting it while it's fading too and see if you get the expected result.

## Additional information

- `[ ]` Changes UI
- `[X]` Introduces new feature
- `[ ]` Removes existing feature
- `[X]` Has associated resource:  #19

2021-08-20 02:54 UTC, lyndsiWilliams approved these changes

2021-08-20 02:54 UTC, lyndsiWilliams commented on Assets/Scripts/AudioController/AudioController.cs
> +        Debug.Assert(_audioSource != null, "AudioController is missing missing AudioSource Component");
Is this meant to have "missing" twice?

2021-08-20 22:31 UTC, TooManyMoths requested changes
Some suggestions, and a request to rework how sound effects are played.

2021-08-20 22:31 UTC, TooManyMoths commented on Assets/Scripts/AudioController/AudioController.cs
> +    [SerializeField] private bool _isTransitioningMusicTracks;
Does this need to be serialized? Would the user ever need to set it manually?

2021-08-20 22:31 UTC, TooManyMoths commented on Assets/Scripts/AudioController/AudioController.cs
> +        yield return null;
Unnecessary yield. Coroutine is already over.

2021-08-20 22:31 UTC, TooManyMoths commented on Assets/Scripts/AudioController/AudioController.cs
> +    }
Making a new audio source for every sound effect feels like an over-complication. Sound effects can be played using PlayOneShot without interrupting the currently playing audio clip. Perhaps make one audio source devoted to sound effects in case they need to make use of AudioSource settings such as pitch.

2021-08-20 22:31 UTC, TooManyMoths commented on Assets/Scripts/AudioController/MusicFader.cs
> +            NormalizedVolume += Time.deltaTime;
Maybe make a multiplier and have a serialized field in AudioController so the fade time can be adjusted.

2021-08-21 16:10 UTC, notexplosive commented on Assets/Scripts/AudioController/MusicFader.cs
> +            NormalizedVolume += Time.deltaTime;
That's... what it already does? AudioController takes the "normalized" value and multiplies it by the volume level scalar.

2021-08-21 16:12 UTC, notexplosive commented on Assets/Scripts/AudioController/AudioController.cs
> +        Debug.Assert(_audioSource != null, "AudioController is missing missing AudioSource Component");
I fixed fixed the typo typo

2021-08-21 16:13 UTC, notexplosive commented on Assets/Scripts/AudioController/AudioController.cs
> +    [SerializeField] private bool _isTransitioningMusicTracks;
It was visible so it was easier to monitor while testing. Un-setting.

2021-08-21 17:02 UTC, notexplosive commented on Assets/Scripts/AudioController/MusicFader.cs
> +            NormalizedVolume += Time.deltaTime;
Done. I went with a divisor instead of multiplier so you're setting a "duration" and not a "speed," I think it's more intuitive this way.

2021-08-21 17:33 UTC, TooManyMoths approved these changes

2021-08-21 17:38 UTC, merged