Feature/actor controller
Studio-Lovelies/GG-JointJustice-Unity pull request #26
Opened 2021-08-23 11:30 UTC by TooManyMoths

## Summary

Implements methods in ActorController (excluding SetActiveSpeaker). Created ActorData scriptable object which holds data about each actor. ActorController loads instances of these objects for each actor and runs their associated animator controller to handle playing of animations and emotions. ActorData instances are loaded from Resources. Contemplated have a scriptable object listing all actors (instead of loading them from disk when needed), but was not sure if it was necessary.

Also modifies DirectorActionDecoder to use a coroutine when decoding actions, so certain actions can have a delay. Added new action WAIT_FOR_ANIMATION (so animations can be played without displaying any text) and modified WAIT action to wait for a number of seconds instead of calling the screen shake method. Also added missing private modifiers and changed "out" parameters in methods to be inline.

## Before/after screenshots and/or animated gif

![guitar](https://user-images.githubusercontent.com/67964179/130438917-8670d9c8-13f6-47ac-a781-ae18e6aad3c9.gif)
The above GIF showcases the WAIT_FOR_ANIMATION and WAIT actions.

## Testing instructions

Open "Actor- TestScene" and play. Press space to progress through the demo.

## Additional information

- `[ ]` Changes UI
- `[x]` Introduces new feature
- `[ ]` Removes existing feature
- `[ ]` Has associated resource:

2021-08-23 17:30 UTC, JuiceGrape requested changes
Very good start, but gonna need some changes. As you mentioned, there were one or two things that could have been prevented if I had the scrum board in order, so my apologies for that. 
Kudos for the error handling and catching the "wait" and "wait_for_end_of_animation" functionality though

2021-08-23 17:30 UTC, JuiceGrape commented on Assets/Resources/InkDialogueScripts/ActorTestInk.ink
> +&EMOTION:Lean
Forgot a &SPEAK:Dan

2021-08-23 17:30 UTC, JuiceGrape commented on Assets/Scripts/Interfaces/IActorController.cs
> +    bool Animating { get; set; }
Please make sure that this is only gettable, not settable publicly. If the system is showing an animation should only ever be set by the ActorController itself

2021-08-23 17:30 UTC, JuiceGrape commented on Assets/Scripts/ActorController.cs
> +        _activeActor = Resources.Load<ActorData>($"Actors/{actor}");
I'd prefer we have a list of these in editor instead of loading them on runtime like this, but I'd like a second opinion on this from a secondary reviewer.

2021-08-23 17:30 UTC, JuiceGrape commented on Assets/Scripts/ActorController.cs
> +            Debug.LogError($"Actor \"{actor}\" could not be found.");
Kudos on the error logging though. Happy to see this

2021-08-23 17:30 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    private IEnumerator PerformActions(string action, string parameters)
Please remove the coroutine functionality from this, as we will probably set this class to be fully separate from unity once we get a script checker in editor.

2021-08-23 17:30 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +            case "WAIT_FOR_ANIMATION": yield return StartCoroutine(WaitForAnimation()); break;
Please move this functionality to the ActorController

2021-08-23 17:30 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +            case "WAIT": yield return StartCoroutine(Wait(parameters)); break;
Please move this functionality to the SceneController

2021-08-23 17:30 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +        StopAllCoroutines();
General remark for this file: onActionDone should only be invoked on actions that are performed instantly. Probably best to move it to the functions that also handle the decoding, so external controllers can just call OnNextLine in the dialogueController themselves

2021-08-23 17:30 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +        StartCoroutine(PerformActions(action, parameters));
General remark: Please revert the changes the formatter made. I'd hate for this file to be re-done fully by every programmer that touches it by the coding style their formatter is set to.
Side note: Turn off your formatter

2021-08-23 17:30 UTC, JuiceGrape commented on Assets/Scripts/ActorController.cs
> +        _spriteRenderer = GetComponent<SpriteRenderer>();
Get the active gameobject representing the actor from the scene controller, and then apply actor changes an animations to that instead, so we can have multiple gameobjects in parallel, with only the one being shown being active,

2021-08-23 17:30 UTC, JuiceGrape commented on Assets/Scripts/ActorController.cs
> +        _spriteRenderer.enabled = true;
With the changes to the active gameobject for the actor being set in the scene manager, showing the actor might be better suited for the scene controller instead of the actor controller. Please move it there and then leave it to be implemented when the scene controller gets implemented.

2021-08-23 17:30 UTC, JuiceGrape commented on Assets/Resources/InkDialogueScripts/ActorTestInk.ink
> +&WAIT_FOR_ANIMATION:
Seeing as this has no parameters, should we maybe change the decoder to handle a function without a ':', or should we make sure this has some parameters? (I think the first one is better)

2021-08-23 17:42 UTC, TooManyMoths commented on Assets/Scripts/ActorController.cs
> +        _activeActor = Resources.Load<ActorData>($"Actors/{actor}");
I also made a version of this where all the actors were listed in a scriptable object. But was unsure whether it was better to load all the actors into memory like that, or just load them as needed.

2021-08-23 17:50 UTC, alipapapupu commented on Assets/Scripts/ActorController.cs
> +        _activeActor = Resources.Load<ActorData>($"Actors/{actor}");
Yeah, I agree. Having hard reference to the objects should be used whenever possible. It makes sure the project stays clean, makes it easier to see all the ActorDatas the game is currently using, keeps the build size smaller and is overall just better option to use on this.

2021-08-23 18:18 UTC, alipapapupu approved these changes
Overall seems good, didn't really find too many improvements that werent mentioned already.

2021-08-23 18:18 UTC, alipapapupu commented on Assets/Scripts/ActorData.cs
> +    public Sprite Profile { get; private set; }
Since these are public, they don't necessarily need the SerializeField. Not wrong to have them, just a remark.

2021-08-23 18:18 UTC, alipapapupu commented on Assets/Scripts/ActorController.cs
>      public void ShowActor()
Why isn't the method commented properly?

2021-08-23 18:58 UTC, JuiceGrape commented on Assets/Scripts/ActorController.cs
>      public void ShowActor()
General remark for this code

2021-08-24 15:22 UTC, bas-mentjot commented on Assets/Scripts/ActorController.cs
> +        _activeActor = Resources.Load<ActorData>($"Actors/{actor}");
A scriptable object seems a bit overkill. What about a prefab?

2021-08-27 17:23 UTC, PhoebeMitchell commented on Assets/Scripts/ActorData.cs
> +    public Sprite Profile { get; private set; }
They are properties so need [field: SerializeField] to be serialized. They are properties to prevent their value being changed by scripts on runtime.

2021-08-27 19:53 UTC, PhoebeMitchell commented on Assets/Scripts/ActorController.cs
> +        _spriteRenderer.enabled = true;
Done. Also moved HideActor to SceneController, updated interfaces, and updated SetActorVisibility method to reflect the change.

2021-08-27 19:54 UTC, PhoebeMitchell commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +        StartCoroutine(PerformActions(action, parameters));
Done

2021-08-27 19:54 UTC, PhoebeMitchell commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    private IEnumerator PerformActions(string action, string parameters)
Done

2021-08-27 19:55 UTC, PhoebeMitchell commented on Assets/Scripts/ActorController.cs
> +        _activeActor = Resources.Load<ActorData>($"Actors/{actor}");
Changed back to the scriptable object solution.

2021-08-27 19:56 UTC, PhoebeMitchell commented on Assets/Scripts/Interfaces/IActorController.cs
> +    bool Animating { get; set; }
Done

2021-08-27 20:06 UTC, PhoebeMitchell commented on Assets/Resources/InkDialogueScripts/ActorTestInk.ink
> +&EMOTION:Lean
Added

2021-08-27 20:18 UTC, PhoebeMitchell commented on Assets/Scripts/ActorController.cs
>      public void ShowActor()
Added summaries to methods with more than one line.

2021-08-27 20:28 UTC, PhoebeMitchell commented on Assets/Resources/InkDialogueScripts/ActorTestInk.ink
> +&WAIT_FOR_ANIMATION:
Actions without parameters no longer require a ':'

2021-08-27 22:33 UTC, PhoebeMitchell commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +        StopAllCoroutines();
Moved onActionDone to the methods called in the switch statement, and OnNextLine is called directly when animations are finished playing.

2021-08-28 19:16 UTC, TooManyMoths commented on Assets/Scripts/ActorController.cs
> +        _spriteRenderer = GetComponent<SpriteRenderer>();
ActorController now has an ActiveActor property which can be set, and communicates with an actor class which handles playing animations.

2021-08-29 15:26 UTC, JuiceGrape approved these changes

2021-08-29 15:31 UTC, merged