Add automated PlayMode and EditorMode tests to GitHub Actions
Studio-Lovelies/GG-JointJustice-Unity pull request #30
Opened 2021-08-24 08:11 UTC by ViMaSter

**Note:** In order for automated tests to work new features would have to be built with tests in mind; so depending on your process of development, this might end up being more work than it's worth. I simply remembered a conversation of it being something that's been considered, so even if these changes themselves don't make it in, maybe it can open up a discussion about the need or expectations for automated testing in the future. Given the still managable scope of the Unity port I just felt like right now would be a good time to introduce it, rather than having to convert a long list of manual testing steps later on.

If this is something you're interested in commiting to, I'd be happy to convert the currently existing manual testing steps of PR's too.  
(So far I think that would only include https://github.com/Studio-Lovelies/GG-JointJustice-Unity/pull/17 and the upcoming https://github.com/Studio-Lovelies/GG-JointJustice-Unity/pull/26 + https://github.com/Studio-Lovelies/GG-JointJustice-Unity/pull/27.)

(And hey, worst case I simply had fun experimenting with automated tests in a proper game project. 👀)

---

## Summary
### Major changes
- Add [Unity Test Runner](https://docs.unity3d.com/2017.4/Documentation/Manual/testing-editortestsrunner.html) PlayMode- and EditorMode-tests to GitHub Actions workflow
- Converted [manual AudioController test scenario](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/pull/21#:~:text=Testing%20instructions,the%20expected%20result.) to PlayMode test

### Minor change
- (Unrelated) Added [editor script](https://github.com/ViMaSter/GG-JointJustice-Unity/blob/workflowtests/Assets/Editor/Scripts/GenerateTargetResolution.cs#L11-L35), which (only if not present) automatically creates and selects a `1280x768`-resolution for the Game-window, eliminating [a step of the first-time setup](https://github.com/ViMaSter/GG-JointJustice-Unity/commit/7b5820c64a5961c8aabcb89589a5b9aca2f20caf#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L37-L38)

## Before/after screenshots and/or animated gif
### Add [Unity Test Runner](https://docs.unity3d.com/2017.4/Documentation/Manual/testing-editortestsrunner.html) PlayMode- and EditorMode-tests to GitHub Actions workflow
This ensures a build (and release) is only triggered, if all automated tests succeed: **(the images are links to their respective runs)**
[![image](https://user-images.githubusercontent.com/1689033/130571950-63cb4a33-9362-4a1e-8b66-0521747acfe6.png)](https://github.com/ViMaSter/GG-JointJustice-Unity/actions/runs/1160370428)
Should the Test Runner fail on any test, the violated assertion and code location is visible on the `Test Results`-tab inside the action details:
[![image](https://user-images.githubusercontent.com/1689033/130571992-95716623-d800-458d-8fec-8e8d2452a29e.png)](https://github.com/ViMaSter/GG-JointJustice-Unity/runs/3405055009?check_suite_focus=true)

---

### Converted [manual AudioController test scenario](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/pull/21#:~:text=Testing%20instructions,the%20expected%20result.) to PlayMode test
Right now, the AudioController can only be tested manually; pressing `A` and `B` on the keyboard inside the `/Assets/Scenes/AudioController - Test Scene.unity` to queue a transition between songs.  
As a proof of concept, I've converted [the manual test](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/bea8fbbb998a1a075db4a93372c9902a63e898cc/Assets/Scripts/AudioController/AudioController.cs#L38-L60) to [an automated script](https://github.com/ViMaSter/GG-JointJustice-Unity/blob/a2c09e82188538031fad9be534eea961b6f05f53/Assets/AutomatedPlayModeTests/AudioController.cs#L33-L68) which validates that the clip name of the AudioSource and it's volume change acordingly, after calling `AudioController.PlaySong()`.

As is evident by the changes of this PR, it is not possible to simply add automated tests "on top" of existing scripts, if the game's scripts are inside the default `Assembly-CSharp`-assembly.  Game code that is to be run inside automated tests, needs to reside in it's own assembly:
1. The only major change of existing code needed to make this work, is that game scripts need to be moved [to a different subfolder other than `Scripts`](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html#:~:text=By%20default%2C%20Unity%20compiles%20almost%20all%20of%20your%20game%20scripts%20into%20the%20predefined%20assembly%2C%20Assembly-CSharp.dll.).
   _In this PR, I've moved the entire `Scripts`-folder into a folder called `GameAssembly`._
2. Then a `.asmdef`-file is created for that folder. (`GameAssembly/Game.asmdef`)  
  This ensures, that all files inside that folder, are compiled into the `Game` Assembly defined inside the `.asmdef`-file.  
  This `.asmdef`-file also contains things like references to the `Ink` library.
3. Another Assembly (one for [`PlayMode`-tests](https://docs.unity3d.com/2017.4/Documentation/Manual/testing-editortestsrunner.html#:~:text=How%20to%20use%20Unity%20Test%20Runner) and one for [`EditorMode`-tests](https://docs.unity3d.com/2017.4/Documentation/Manual/testing-editortestsrunner.html#:~:text=Testing%20in%20Edit%20mode)) is created.  
   _In this PR I've only created a folder called `PlayModeTestAssembly`, as no `EditMode`-tests are added._
  This again ensures, that all files inside that folder, are compiled into the `PlayModeTest` Assembly defined inside the `.asmdef`-file. This `.asmdef`-File also adds a reference to the `Game`-assembly; that way, the `PlayModeTest` scripts can access the `Game`-scripts. That way, automated test scripts are also never compiled into any Release build of the game.
4. After that, NUnit-style test suits - like the one for the [AudioController](https://github.com/ViMaSter/GG-JointJustice-Unity/blob/a2c09e82188538031fad9be534eea961b6f05f53/Assets/AutomatedPlayModeTests/AudioController.cs) - can be created.

## Testing instructions
Either...
* open the project in Unity
* open the Unity Test Runner windows using `Window`->`General`->`Test Runner`
* click `PlayMode` at the top of the window
* click `Run All`
* wait for the tests to run and pass

OR

* run the GitHub Workflow after merging this PR (or in a fork of my changes)

## Additional information

- `[ ]` Changes UI
- `[x]` Introduces new feature:
  - automated AudioController test
- `[x]` Removes existing feature
  - AudioController Keyboard Listener
  - AudoController automatically starts playing `aBoyAndHisTrial`
- `[ ]` Has associated resource:

2021-08-24 13:39 UTC, ViMaSter commented
I just realized, https://github.com/Studio-Lovelies/GG-JointJustice-Unity/pull/27 is already setting up Test Assemblies to use. I think waiting for it to be merged into `develop` and then rebasing these changes would make the most sense here?

2021-08-24 15:23 UTC, bas-mentjot commented
> I just realized, #27 is already setting up Test Assemblies to use. I think waiting for it to be merged into `develop` and then rebasing these changes would make the most sense here?

Agreed, we'll get that through first

2021-08-24 15:24 UTC, JuiceGrape commented
> I just realized, #27 is already setting up Test Assemblies to use. I think waiting for it to be merged into `develop` and then rebasing these changes would make the most sense here?

Agreed, block this till that pr is pushed through

2021-08-29 11:47 UTC, ViMaSter commented
@JuiceGrape Rebased this branch to `develop` and reintroduced my changes (hence the force-push).  
I've updated [the top post](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/pull/30#issue-977830050) to contain all the changes that are now actually still present in it.

2021-09-02 14:53 UTC, notexplosive approved these changes
Wow, thanks for doing all this! Sorry we keep stepping on this branch, I'll see if we can get it merged in soon.

Your changes delete many of our `.ink`/`.json` files as well as some of our test scenes. Although it makes sense to get rid of these eventually (as we replace manual tests with automated tests) I don't think we're quite ready to get rid of these quite yet. Although it's nice to have gated checks for automated testing, it's also nice to be able to visually see the game working in local development.

Marking as "Approve" assuming you'll act on the above feedback and comments :)

2021-09-02 14:53 UTC, notexplosive commented on Assets/Scripts/AudioController/AudioController.cs
> -        PlaySong("aBoyAndHisTrial");
This code (and the other `// DEBUG` code below) are already removed in `develop`, there have also been a few changes and refactors on top of this. I think you can revert your changes to this file (which will save you some merge conflict headache)

2021-09-02 14:53 UTC, notexplosive commented on Assets/Scripts/Menu/Menu.cs
> +    public bool Active => gameObject.activeInHierarchy && SelectedButton && SelectedButton.interactable; // Returns true when no child menus are active ONLY if this menu is enabled
nit: Is this a null check? If so I prefer the slightly more verbose `SelectedButton != null` (maybe even extracted into a method `HasSelectedButton()`)

Minor nitpick, feel free to ignore

2021-09-02 14:53 UTC, notexplosive commented on Assets/Scripts/TextDecoder/DialogueController.cs
> -    [SerializeField] private TextAsset _narrativeScript;
We're losing this serialized field. Maybe I'm missing it but how do you specify the current narrative script in the game scene then?

2021-09-02 14:53 UTC, notexplosive commented on Assets/Tests/PlayModeTests/Scripts/AudioController/AudioController.cs
> +    public class AudioController
The name duplication here confused me. If a test class is meant to test one "product" class (like this one) I prefer to see the name "Test" somewhere in the name of the class. Which is to say: can you rename this class/file to `AudioControllerTests`?

2021-09-02 14:53 UTC, notexplosive commented on Assets/Tests/PlayModeTests/Scripts/DialogueController/DialogueController.cs
> +    public class DialogueController
Ditto here about the class name, my preference would be `DialogueControllerTests`

2021-09-02 14:53 UTC, notexplosive commented on Assets/Editor/Scripts/GenerateTargetResolution.cs
> +        private static readonly (string name, int width, int height) ResolutionData = ("Game Grumps - Joint Justice", 1280, 768);
I see you got this from the README, which was the right thing to do. But of course our docs are out of date.

The game is expected to run at any 16:9 resolution, for most practical cases that means 1920x1080, but it should also work in 4K or 1280x720. It should also be able to run on a 4:3 or ultrawide screen with black bars filling the gaps. Just to give you some context as to where we're thinking.

2021-09-04 09:25 UTC, ViMaSter commented on Assets/Scripts/TextDecoder/DialogueController.cs
> -    [SerializeField] private TextAsset _narrativeScript;
Inside `DialogueController.Start()` there's `SetNarrativeScript(_narrativeScript); //TODO:Disable this, for debug only`.  
That and the existance of `DialogueController.SetNarrativeScript()` made it sound like the script shouldn't initialize itself and (similarly to the AudioController) only does so for testing purposes. However I'll make sure to restore the property!

2021-09-04 09:26 UTC, ViMaSter commented on Assets/Editor/Scripts/GenerateTargetResolution.cs
> +        private static readonly (string name, int width, int height) ResolutionData = ("Game Grumps - Joint Justice", 1280, 768);
No worries; and makes sense! I've seen that README was updated when rebasing onto `develop` again and I have removed that editor script since there's no need for it anymore.

2021-09-04 09:36 UTC, ViMaSter commented
Rebased onto `develop` and addressed all of the requested changes. The change also now also no longer deletes the manual testing scenes!

I'm used to authors marking conversations as resolved once they see their requested changes implemented, but also have seen some PRs on here where it works the other way around. Let me know which way you prefer, either here or on Discord!

2021-09-04 17:31 UTC, lyndsiWilliams approved these changes

2021-09-04 17:31 UTC, lyndsiWilliams commented on Assets/Scripts/UILogic/QuitGame.cs
> +    public void ExecuteQuit()
✨ This method is missing a summary ✨

2021-09-04 17:31 UTC, lyndsiWilliams commented on Assets/Tests/PlayModeTests/Scenes/MainMenu/ViaKeyboard.cs
> +            var menus = Resources.FindObjectsOfTypeAll<Menu>();
Could you define the `var`s in this file, or do they need to be `var`s?

2021-09-04 17:31 UTC, lyndsiWilliams commented on Assets/Tests/PlayModeTests/Scenes/MainMenu/ViaMouse.cs
> +            var menus = Resources.FindObjectsOfTypeAll<Menu>();
Same as the previous comment, could you define the `var`s in this file, or do they need to be `var`s?

2021-09-04 17:31 UTC, lyndsiWilliams commented on Assets/Tests/PlayModeTests/Scripts/AudioController/AudioControllerTests.cs
> +            var audioControllerGameObject = new GameObject("AudioController");
Also same as the previous comments, could you define the `var`s in this file, or do they need to be `var`s?

2021-09-04 17:31 UTC, lyndsiWilliams commented on Assets/Tests/PlayModeTests/Scripts/DialogueController/DialogueControllerTests.cs
> +            var dialogueControllerGameObject = new GameObject("DialogueController");
Also also same as the previous comments, could you define the `var`s in this file, or do they need to be `var`s?

2021-09-04 17:36 UTC, notexplosive approved these changes, later dismissed

2021-09-04 18:00 UTC, ViMaSter commented on Assets/Scripts/UILogic/QuitGame.cs
> +    public void ExecuteQuit()
[Added](https://github.com/ViMaSter/GG-JointJustice-Unity/blob/627a82fac2e127f170c1142aa08562e7c53c9a58/Assets/Scripts/UILogic/QuitGame.cs#L18)!

2021-09-04 18:00 UTC, ViMaSter commented on Assets/Tests/PlayModeTests/Scenes/MainMenu/ViaKeyboard.cs
> +            var menus = Resources.FindObjectsOfTypeAll<Menu>();
Definitely not needed! Just my linter applying preferences from my other projects; I've changed all `var`s to their explicit type.

2021-09-04 18:00 UTC, ViMaSter commented on Assets/Tests/PlayModeTests/Scenes/MainMenu/ViaMouse.cs
> +            var menus = Resources.FindObjectsOfTypeAll<Menu>();
[Updated as well!](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/pull/30#discussion_r702311736)

2021-09-04 18:00 UTC, ViMaSter commented on Assets/Tests/PlayModeTests/Scripts/AudioController/AudioControllerTests.cs
> +            var audioControllerGameObject = new GameObject("AudioController");
[Updated as well!](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/pull/30#discussion_r702311736)

2021-09-04 18:00 UTC, ViMaSter commented on Assets/Tests/PlayModeTests/Scripts/DialogueController/DialogueControllerTests.cs
> +            var dialogueControllerGameObject = new GameObject("DialogueController");
[Updated as well!](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/pull/30#discussion_r702311736)

2021-09-04 18:31 UTC, lyndsiWilliams submitted a review, later dismissed

2021-09-04 18:31 UTC, lyndsiWilliams commented on README.md
> -- (First Time Only) If you see the "Free Aspect", click on it
Why is this being removed? Is it not a thing anymore?

2021-09-04 21:54 UTC, lyndsiWilliams commented on README.md
> -- (First Time Only) If you see the "Free Aspect", click on it
Disregard, I missed this bit in your description:
- (Unrelated) Added editor script, which (only if not present) automatically creates and selects a 1280x768-resolution for the Game-window, eliminating a manual step of the first-time setup

My bad! 😅

2021-09-06 19:31 UTC, notexplosive approved these changes, later dismissed

2021-09-07 09:53 UTC, ViMaSter commented
Rebased it onto `develop`. Again. : }  

Builds failed after utilizing `yield return WaitForEndOfFrame()` which [isn't supported](https://docs.unity3d.com/2021.1/Documentation/Manual/CLIBatchmodeCoroutines.html#:~:text=Yes-,WaitForEndOfFrame,No*,-Yes) when executing the editor [headless](https://docs.unity3d.com/Manual/CommandLineArguments.html#:~:text=Run%20Unity%20in,the%20-buildTarget%20option.). This should now be addressed.

The only other notable changes are:
### [Assets/Scripts/SceneLoading/SceneLoader.cs](https://github.com/ViMaSter/GG-JointJustice-Unity/commit/37514ce1e5d71a69bae3f3fce69bf24a7d4d2291#diff-dc018ae26c2d6ec33d7ec2fc844b3399fa910edb847c00c54db1ba2b052cef80R55-R72)
- Inside the unit test frameworks we have to mock scene loading, which resulted in NullReferenceExceptions; I have wrapped the affected lines accordingly
### [Assets/Scripts/Input/UnityInputSystemInterface.cs](https://github.com/ViMaSter/GG-JointJustice-Unity/commit/1a95925038b52b7c2776396521bd4918283d451d#diff-32ed8d39f2c0fb7ec981bd734c3a712d0016f4593149f7b202b2a76f36789ad1R42-R94)
- This script now cleans up when being disabled (not doing it results in dangling pointers and a bunch of low-level UnityEngine exceptions when the scene is reloaded)

2021-09-07 15:07 UTC, notexplosive submitted a review, later dismissed

2021-09-07 19:59 UTC, lyndsiWilliams approved these changes, later dismissed
Lookin' good! _marge it quick before the merge conflict gnomes notice_ 😬

2021-09-09 01:34 UTC, TooManyMoths reviewed
Really cool stuff here. All the tests run and pass. Just got a few questions.

2021-09-09 01:34 UTC, TooManyMoths commented on Assets/Scripts/UILogic/QuitGame.cs
> +        UnityEditor.EditorApplication.isPlaying = false;
Would this not immediately quit without waiting for a transition?

2021-09-09 01:34 UTC, TooManyMoths commented on Assets/Scripts/UILogic/QuitGame.cs
> +        _transitionController.Transition();
This probably needs a null check in case no transition is desired.

2021-09-09 01:34 UTC, TooManyMoths commented on Assets/Tests/PlayModeTests/Scripts/AudioController/AudioController.cs
> +    public class AudioController
Was this going to be renamed to AudioControllerTests? I find it kind of confusing too. Same for the other test classes.

2021-09-09 02:02 UTC, ViMaSter commented
@TooManyMoths Thanks for the review! When rebasing the changes, I seem to have used an older version of my changes, which resulted in already-discussed items being wrong again, sorry for that and good job spotting it!

Similarly the "Quit game"-button was still using the transition controller incorrectly and I've reintroduced the changes from last time (adding a second GameObject with a second TransitionController and using that for the "quit game" button + splitting "queuing of a transition" and "actually quitting the game after the transition is complete" it into two event callbacks, called on button press and transition end respectively.)

2021-09-09 02:09 UTC, TooManyMoths approved these changes

2021-09-09 02:49 UTC, TooManyMoths requested changes

2021-09-09 02:49 UTC, TooManyMoths commented on Assets/Scripts/SceneLoading/SceneLoader.cs
> -            return;
Removing this means scene is loaded instantly without waiting for transition.

2021-09-09 02:49 UTC, TooManyMoths commented on Assets/Scripts/SceneLoading/SceneLoader.cs
> +            }
Setting this back to true before the transition is complete means the scene will be loaded instantly

2021-09-09 02:49 UTC, TooManyMoths commented on Assets/Scripts/SceneLoading/SceneLoader.cs
>          }
Loading bar is enabled in LoadSceneCoroutine so doesn't need to be here.

2021-09-09 14:58 UTC, ViMaSter commented
@TooManyMoths Good catch! Another set of unintentional changes during rebasing; (as the PR originated back when the TransitionController `yield`ed)... : S  
Implemented all of the requested changes, thanks for spotting them!

---

Was hoping I could cover "waiting for a transition" with another test case, but all properties inside `AsyncOperation` (which is returned by `LoadSceneAsyncByNameOrIndex()`) are `extern`al memory which can't be overloaded via Reflection.

2021-09-09 15:10 UTC, TooManyMoths approved these changes

2021-09-09 18:12 UTC, lyndsiWilliams approved these changes
_stamp_ ✅ SHIP THOSE SWEET TESTS BB ✨

2021-09-09 18:43 UTC, merged