Feature/20 appearing dialog
Studio-Lovelies/GG-JointJustice-Unity pull request #32
Opened 2021-08-26 17:34 UTC by alipapapupu

## Summary

Created script that makes letters appear one at a time to the screen. You are able to change the speed of punctuation, dialog, or overall speed from the inky file. The code has function ready to speed up the dialog when player gives input, and this feature can be disabled/enabled from the inky file. You can prolong the dialog with next one after players input, or make the dialogs skip to next one without players input.

Does not change the speakers name or background color yet. For this I would request new PR implementing Scriptable Object containing the name, color etc. information about the speaker, and this could be used to changed all information on the screen.
 
## Before/after screenshots and/or animated gif

Example of the dialog appearing
![AppearingDialog](https://user-images.githubusercontent.com/16340242/131007291-c351d506-285a-48e2-98a7-23bb58e73603.gif)

## Testing instructions

Open AppearingText-TestScene and hit play. The textbox contains Lorem Ipsum, but after you press space, the dialog starts. Take a look at the AppearingDialogInk-file while testing the dialog to see how they affect the way dialog appears.

## Additional information

- `[x]` Changes UI
- `[x]` Introduces new feature
- `[ ]` Removes existing feature
- `[x]` Has associated resource:  #20

2021-08-26 22:13 UTC, JuiceGrape requested changes
Needs some work. Particularly sticking to existing code structures and moving logic out of existing classes where it doesn't belong.

2021-08-26 22:13 UTC, JuiceGrape commented on Assets/Resources/InkDialogueScripts/AppearingDialogInk.ink
> +&FORCE_NEXT_DIALOG:
I think it's better to replace this with "AUTO_SKIP:True" and "AUTO_SKIP:False". Just having auto skip enabled until we disable it seems like a more logical way of doing this than defining it for every line

2021-08-26 22:13 UTC, JuiceGrape commented on Assets/Resources/InkDialogueScripts/AppearingDialogInk.ink
> +&DISABLE_SKIPPING:TRUE
What would DISABLE_SKIPPING:False do? For that matter, what does DISABLE_SKIPPING:True do?

2021-08-26 22:13 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DialogueController.cs
> +    public void StopWritingDialog()
Good way of solving this externally. However, button logic will not be handled in here, as it being in here was for debug purposes only (as denoted by the comment). Maybe create an "inputHandler" class which takes button presses and then triggers functions (through events) in the correct places? 
Basically I think it's best to have all input handling logic in it's own class, separate from the DialogueController

2021-08-26 22:13 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    [Header("Basic Values")]
Please remove these and add them like we have before. This class needs to be completely agnostic from anything external

2021-08-26 22:13 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +        if (float.TryParse(seconds, out timeInSeconds))
Please refrain from changes like this as they fog up git. Revert if you can

2021-08-26 22:13 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +        if (float.TryParse(seconds, out timeInSeconds))
In other places as well, I trust your judgement on finding them

2021-08-26 22:13 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +    private bool HasAppearingDialogController()
Move to controller stuff

2021-08-26 22:13 UTC, JuiceGrape commented on Assets/Scripts/UI/AppearingDialogController.cs
> +public class AppearingDialogController : MonoBehaviour
Add interface

2021-08-26 22:13 UTC, JuiceGrape commented on Assets/Scripts/UI/AppearingDialogController.cs
> +    public UnityEvent DialogDoneEvent { get { return _dialogDoneEvent; } }
Why does this exist? We should not be linking events in code, unless in special cases. This has no reason to be public

2021-08-26 22:13 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DialogueController.cs
> +    public void StopWritingDialog()
Quick thought: We should probably make it a state machine

2021-08-26 22:13 UTC, JuiceGrape commented on Assets/Scripts/UI/AppearingDialogController.cs
> +    static private bool GetFloatFromString(string dialogText, float previousTime, out float newAppearTime)
This description makes no sense to me. What does this function do? The name is kinda bad too, cause getting a float from a string is just float.parse(string)

2021-08-26 22:13 UTC, JuiceGrape commented on Assets/Scripts/UI/AppearingDialogController.cs
> +    private class WaitInformation
Probably better as a struct?

2021-08-26 22:13 UTC, JuiceGrape commented on Assets/Scripts/UI/AppearingDialogController.cs
> +    }
Rest of the class looks great, keep up the good work.

2021-08-26 22:57 UTC, alipapapupu commented on Assets/Resources/InkDialogueScripts/AppearingDialogInk.ink
> +&DISABLE_SKIPPING:TRUE
DISABLE_SKIPPING:True makes it so player cant speed up or skip the dialog at all, rather, it will appear in constant speed. Good if dialog needs to be timed to appear with the animation, otherwise the player could speed up the dialog and screw things up. DISABLE_SKIPPING:False just makes the speeding possible again. If you have better names for this, I would be glad to hear them.

2021-08-26 22:58 UTC, alipapapupu commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +        if (float.TryParse(seconds, out timeInSeconds))
Sure, my bad. I tend to auto format everything, and its in my muscle memory, but I'll see what I can do.

2021-08-26 23:00 UTC, alipapapupu commented on Assets/Scripts/UI/AppearingDialogController.cs
> +    static private bool GetFloatFromString(string dialogText, float previousTime, out float newAppearTime)
Legacy code from my original version, I can just delete the whole function.

2021-08-27 01:20 UTC, PhoebeMitchell approved these changes
Some suggestions, but overall the code looks functional, and runs as expected. AppearingDialogController is very big though. Could it be split up? It should also be be Dialogue instead of Dialog, as it's referring to conversation and not computer dialog boxes.

Not sure if having a mask to colour the textbox is necessary, when you could just set the colour of the mask image itself. I feel it would be easier to position text if the name box and the speech box were separate sprites. Then you could just get the speech text to fill the whole size of the speech box, and it would allow for easier position of the name text too.

Also correct the spelling of general in GerenralSpeechPanel. Then make the changes requested by JuiceGrape and it should be good.

2021-08-27 01:20 UTC, PhoebeMitchell commented on Assets/Scripts/TextDecoder/DialogueController.cs
> +    public void StopWritingDialog()
UnityInputSystemInterface is now in the develop branch if you need an input class.

2021-08-27 01:20 UTC, PhoebeMitchell commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +        bool value = bool.Parse(disabled);
Consider using TryParse for error checking, and to be consistent with the rest of the script.

2021-08-27 01:20 UTC, PhoebeMitchell commented on Assets/Scripts/UI/AppearingDialogController.cs
> +    private TextMeshProUGUI _controlledText = null;
nit: Do not need to initialise fields if the value is the field's default value.

2021-08-27 01:20 UTC, PhoebeMitchell commented on Assets/Scripts/UI/AppearingDialogController.cs
> +        _temporaryDialogDoneEvent.RemoveAllListeners();
Add ? for null check, like on previous line.

2021-08-27 01:20 UTC, PhoebeMitchell commented on Assets/Scripts/UI/AppearingDialogController.cs
> +            _temporaryDialogDoneEvent.AddListener(ua);
Could you just loop through the dialogDoneActions and invoke each one? Instead of subscribing them all to an event.

2021-08-27 01:20 UTC, PhoebeMitchell commented on Assets/Scripts/UI/AppearingDialogController.cs
> +                _allWaiters[WaiterTypes.letter].inUse = false;
Add braces to if statement.

2021-08-27 01:20 UTC, PhoebeMitchell commented on Assets/Scripts/UI/AppearingDialogController.cs
> +    ///Read the commands from dialog and seperates them. Prototype, currently not in use.
spelling: separates

2021-08-27 01:20 UTC, PhoebeMitchell commented on Assets/Scripts/UI/AppearingDialogController.cs
> +                else if (!insideCommand)
Use else instead of else if

2021-08-27 01:20 UTC, PhoebeMitchell commented on Assets/Scripts/UI/AppearingDialogController.cs
> +    ///Read the commands from dialog and seperates them. Prototype, currently not in use.
By prototype do you mean these methods will be used in future, or that they are no longer used? Can they be removed?

2021-08-27 01:20 UTC, PhoebeMitchell commented on Assets/Scripts/UI/AppearingDialogController.cs
> +            _currentAppearTime = _allWaiters[newWaiter].waitTime;
Punctuation speed affects things it probably shouldn't such as apostrophes, and symbols such as $ and £.

2021-08-27 01:20 UTC, PhoebeMitchell commented on Assets/Scripts/UI/AppearingDialogController.cs
> +        public bool useWithEverything = false;
These should be properties, and in PascalCase

2021-08-27 01:20 UTC, PhoebeMitchell commented on Assets/Scripts/UI/AppearingDialogController.cs
> +        public WaitInformation() { }
Remove duplicate constructor.

2021-08-27 01:20 UTC, PhoebeMitchell commented on Assets/Scripts/UI/WaiterTypes.cs
> +    defaultValue,
Consider changing WaiterTypes to WaiterType and using PascalCase for values to follow C# conventions.
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces

2021-08-28 10:29 UTC, JuiceGrape commented on Assets/Resources/InkDialogueScripts/AppearingDialogInk.ink
> +&DISABLE_SKIPPING:TRUE
Ah good thing to have indeed

2021-08-28 10:31 UTC, JuiceGrape commented on Assets/Scripts/UI/AppearingDialogController.cs
> +    static private bool GetFloatFromString(string dialogText, float previousTime, out float newAppearTime)
Legacy code should be removed unless you specifically intent to refactor or re-use it later

2021-08-28 10:32 UTC, JuiceGrape commented on Assets/Scripts/UI/AppearingDialogController.cs
> +        _temporaryDialogDoneEvent.RemoveAllListeners();
What is the alternate course for a ? null check? If it's just ignoring the line, I'd prefer to make those null checks explicit in it's own line which aborts any future functionality

2021-08-28 10:34 UTC, JuiceGrape commented on Assets/Scripts/UI/AppearingDialogController.cs
> +        public bool useWithEverything = false;
Also, this seems like state behaviour, so it should be an enum instead of 2 bools. If neither of these can be true at the same time that is

2021-08-28 14:10 UTC, alipapapupu commented on Assets/Scripts/UI/AppearingDialogController.cs
> +    private TextMeshProUGUI _controlledText = null;
I know, but Unity used to give warnings in the editor whenever a SerializeField or public value wasn't initialised in the code even though it would get initialised in the editor. They did fix this like a year ago, but it's already in my muscle memory to initialise values with the fields default value, and I will probably keep doing it even though it's a bit pointless.

2021-08-28 14:51 UTC, alipapapupu commented on Assets/Scripts/UI/AppearingDialogController.cs
> +    ///Read the commands from dialog and seperates them. Prototype, currently not in use.
It depends on what we decide and what the designer team wants. Right now the speeds can be changed only before the dialog happens. Things markes as prototype would give full control over how the dialog is shown, giving the possibility to change speed values in the middle of the dialog and thus giving possibility to make more it complex, speeding and slowing when wanted. If we deem this unnecessary, I can remove everything marked as prototype, but I would like to hear yours and @JuiceGrape opinion on it, do we/design/writer team need that much control?

2021-08-28 19:50 UTC, TooManyMoths commented on Assets/Scripts/UI/AppearingDialogController.cs
> +        _temporaryDialogDoneEvent.RemoveAllListeners();
For regular C# events it checks if the event has any listeners and is the same as checking "event != null".
I found out today thought it's not necessary for Unity Events. '?' checks if the UnityEvent object itself is null, which it probably isn't if it's serialised.

2021-08-28 19:52 UTC, TooManyMoths commented on Assets/Scripts/UI/AppearingDialogController.cs
> +    ///Read the commands from dialog and seperates them. Prototype, currently not in use.
I think this feature would be cool, but ask the design team what they're expecting. No point putting the effort in if they don't want it.

2021-08-29 10:07 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DirectorActionDecoder.cs
> +        Debug.LogError("Bool value wasn't found from command. Please fix.");
Nondescript error message doesn't help anyone. Put the error message in the decode function, which sorta eliminates the need for having this a separate function.

2021-08-29 11:29 UTC, alipapapupu commented on Assets/Scripts/TextDecoder/DialogueController.cs
> +    public void StopWritingDialog()
Fixed the issue. DialogueAppearController takes care of the autoSkip feature, and calls the OnNextLine when autoskip should happen. DialogueController also has bool that is changed by DialogueAppearControllers events to make sure dialog doesn't overlap, and it's not connected to the input in any way anymore.

2021-08-29 11:30 UTC, alipapapupu commented on Assets/Scripts/UI/AppearingDialogController.cs
> +    public UnityEvent DialogDoneEvent { get { return _dialogDoneEvent; } }
made private, and deleted extra event

2021-08-29 11:30 UTC, alipapapupu commented on Assets/Scripts/UI/AppearingDialogController.cs
> +    static private bool GetFloatFromString(string dialogText, float previousTime, out float newAppearTime)
Refactored the method to work smarter way, and deleted unnecessary legacy code.

2021-08-29 11:31 UTC, alipapapupu commented on Assets/Scripts/UI/AppearingDialogController.cs
> +    private class WaitInformation
Since the inUse and waitTime-values of the class is changed constantly, this being a struct won't work because that would require recreating the vakkye every time these values need to change.

2021-08-29 12:07 UTC, alipapapupu commented on Assets/Scripts/UI/AppearingDialogController.cs
> +    ///Read the commands from dialog and seperates them. Prototype, currently not in use.
I'll leave these in for now, since there might be need for them later, but what we have right now seemed to be enough for people.

2021-08-29 12:08 UTC, alipapapupu commented on Assets/Scripts/UI/AppearingDialogController.cs
> +            _temporaryDialogDoneEvent.AddListener(ua);
Removed the whole function since it was quite unnecessary

2021-08-29 12:30 UTC, JuiceGrape approved these changes

2021-08-29 13:03 UTC, merged