Support for `Talk` and `Move` inside investigation sections
Studio-Lovelies/GG-JointJustice-Unity pull request #460
Opened 2024-08-24 18:31 UTC by ViMaSter

## Summary
Since this was a work-in-progress branch, viewing individual commits isn't super useful. I've broken down my changes by files below, I'd recommend looking at those first and then at the remaining files.

### Known issues (done to keep PRs _somewhat_ small)

- `Examine` and `Present` are currently unhandled. They might work, they might not, and they're neither covered nor implemented. They're outlined inside #456 however.
- After selecting `Move` or `Talk`, the player can't go back to the main menu, other than selecting an option and playing through it. The logic is currently unhandled and might open up weird edge cases, as (aside from the evidence menu) we haven't had UI that allowed you to "go back one step" in the game loop. I'll probably leverage whatever we've used for the main menu setting menus for that in another PR.

### Features added
#### Minor stuff up front:

- Reloading the game in the background was pretty annoying, so I bound the in-game editor and hot-reloading to `Ctrl/Command+R`, rather than just `R`.
  - `unity-ggjj/Assets/Scripts/Input/DebugControls.cs`
  - `unity-ggjj/Assets/Tests/PlayModeTests/Suites/Scripts/RuntimeEditingTests.cs`

-  Adjusted the default audio levels; open up your average YouTube video, set your volume to a comfortable level, and the game should(!) no longer blow out your eardrums.
  This _is_ reflected in the settings menu however and probably shouldn't. Ideally the game starts at 80% master and 100% for the rest, no matter our internal mixing. I'll create a separate issue for that.  
  Also added ducking/side-chaining of the music whenever SFX play.  
  ![image](https://github.com/user-attachments/assets/018ce985-7093-4537-92bc-1669accc49dd)
    - `unity-ggjj/Assets/GameAudioMixer.mixer`
  
---

#### The new game state: Investigation. This PR adds `Talking` and `Moving` based on #456.

- Reference script: https://gist.github.com/ViMaSter/7606b62d0405d173ddfa6e51fb2ed671  
(also added under `unity-ggjj/Assets/Tests/PlayModeTests/TestScripts/InvestigationUI.ink`). 
- Demo:
  
  https://github.com/user-attachments/assets/267ae133-3ada-4493-a3c6-42a3a73ec312

Technical details of the implementation:

Based on a great recommendation from @moths, this leverages Ink's [choices](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#2-choices), [knots](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#3-knots) and [tags](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#tags).  
`&MODE:Dialogue` already had choices, so I've added `&MODE:Investigation`, which just splits them up into `Talk` and `Move` choices based on [tags](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#tags).  
For readability I've split up the `Gameplay` region in the code further into `CrossExamination` and `Investigation`.
- `unity-ggjj/Assets/Scripts/TextDecoder/ActionDecoder.cs`
- `unity-ggjj/Assets/Scripts/TextDecoder/Parser/ChoiceTypeParser.cs`
- `unity-ggjj/Assets/Tests/EditModeTests/Suites/TextDecoder/ActionDecoderTests/ImplementationTests.cs`

I've also added a new class, `InvestigationState`, to the `NarrativeGameState`: `InvestigationState.OpenWithChoices()` is called, when encountering Ink choices while in the `&MODE:Investigation`. It's responsible for handling navigation through the Investigation UI and keeping track of which choices belong to `Move`/`Talk` and if they're unlocked yet.
- `unity-ggjj/Assets/Scripts/GameState/IInvestigationState.cs`
- `unity-ggjj/Assets/Scripts/GameState/InvestigationState.cs`
- `unity-ggjj/Assets/Scripts/GameState/INarrativeGameState.cs`
- `unity-ggjj/Assets/Scripts/GameState/NarrativeGameState.cs`

The investigation main menu is static and contains the four buttons:
- `unity-ggjj/Assets/Game/Scenes/Game.unity/BaseCanvas/InvestigateMainMenu`

For the buttons:
- `Examine` and `Present` are unhandled in this PR, as mentioned in the summary.
- `Talk` opens `…/BaseCanvas/InvestigateTalkMenu`; this is a simple `ChoiceMenu` like we used in Case1, and `InvestigationState.OpenTalkMenu()` is called when clicking the button, which instantiates choice button prefabs.
- `Move` opens `…/BaseCanvas/InvestigateMoveMenu`; this contains a simple `ChoiceMenu`, but also contains the preview image of the next scene. The choice references a scene and the background thereof is used as the preview image. `InvestigationState.OpenMoveMenu()` is called when clicking the button, which instantiates choice button prefabs and updates the preview image.

![image](https://github.com/user-attachments/assets/fdda2253-4987-468f-979d-e850e2050495)

The`InvestigationState` also hides choices tagged with `#Locked` until the player crosses an `&UNLOCK_CHOICE` action line.  
- `unity-ggjj/Assets/Scripts/NarrativeScript/GameMode.cs`
- `unity-ggjj/Assets/Scripts/NarrativeScript/NarrativeScriptPlayer/NarrativeScriptPlayer.cs`

## Testing instructions
- Play the newly added `.ink` scene

## Additional information

- `[x]` Changes UI
- `[x]` Introduces new feature
  - Investigation main menu, `Talk` and `Move` submenu, unlocking `Talk` and `Move` choices
- `[ ]` Removes existing feature
- `[x]` Has associated resource: 
  - #456

2024-08-26 14:42 UTC, PhoebeMitchell requested changes
Looks super, and works really well! Great job! A few code stuffs, and many nitpicks.

2024-08-26 14:42 UTC, PhoebeMitchell commented on .github/workflows/remove_debug_script.yml
> +name: Remve debug narrative script
```suggestion
name: Remove debug narrative script
```

2024-08-26 14:42 UTC, PhoebeMitchell commented on docs/methods/Progression.md
> +  - `&UNLOCK_CHOICE:Nice Coat,Talk`
Subjective, but to me something like this would make more sense as seperate actions as opposed to having the Move/Talk as an argument. Something like UNLOCK_MOVE_CHOICE/UNLOCK_TALK_CHOICE

2024-08-26 14:42 UTC, PhoebeMitchell commented on docs/constants.md
> +  - INVESTIGATIONTESTFAIL2
What are these for? Is it possible to fail an investigation? They don't appear to be used as far as I can see, and currently they are just duplicates of the other fail scripts. Can they be removed?

2024-08-26 14:42 UTC, PhoebeMitchell commented on unity-ggjj/Assets/Scripts/GameState/IInvestigationState.cs
> +
```suggestion
```

2024-08-26 14:42 UTC, PhoebeMitchell commented on unity-ggjj/Assets/Scripts/GameState/InvestigationState.cs
> +    [SerializeField] private ChoiceMenu InvestigationMoveMenu;
Should follow save naming scheme as the other private variables `_camelCase`

2024-08-26 14:42 UTC, PhoebeMitchell commented on unity-ggjj/Assets/Scripts/GameState/InvestigationState.cs
> +    private readonly List<string> _examinedChoices = new();
Doesn't appear to be used. Planned for when Examine is added?

2024-08-26 14:42 UTC, PhoebeMitchell commented on unity-ggjj/Assets/Scripts/GameState/InvestigationState.cs
> +    // ReSharper disable Unity.PerformanceAnalysis
Personally I'd rather have the little green line under OpenMenu than a whole line dedicated to disabling it.
```suggestion
```

2024-08-26 14:42 UTC, PhoebeMitchell commented on unity-ggjj/Assets/Scripts/GameState/InvestigationState.cs
> +        var selectableAndLabel = InvestigationMoveMenu.transform.GetComponentsInChildren<MenuItem>().Select(menuItem => (menuItem, menuItem.GetComponentInChildren<TextMeshProUGUI>().text)).ToList();
Very long line. Can it be spread over a few lines like below? Also the `transform` is redundant.

```suggestion

        var selectableAndLabel = InvestigationMoveMenu
            .GetComponentsInChildren<MenuItem>()
            .Select(menuItem => (menuItem, menuItem.GetComponentInChildren<TextMeshProUGUI>().text))
            .ToList();
        
```

2024-08-26 14:42 UTC, PhoebeMitchell commented on unity-ggjj/Assets/Scripts/GameState/InvestigationState.cs
> +        foreach (var valueTuple in selectableAndLabel)
If a tuple is necessary, I think this syntax is a little more consise. Saves writing lots of `valueTuple`s

```suggestion
        foreach (var (menuItem, text) in selectableAndLabel)
```

2024-08-26 14:42 UTC, PhoebeMitchell commented on unity-ggjj/Assets/Scripts/GameState/InvestigationState.cs
> +        var selectableAndLabel = InvestigationMoveMenu.transform.GetComponentsInChildren<MenuItem>().Select(menuItem => (menuItem, menuItem.GetComponentInChildren<TextMeshProUGUI>().text)).ToList();
There's not much point in making a tuple here. You can just do the GetComponent when looping over all the menuItems or, preferably, MenuItem already has a reference to it's text so just expose a property on it.

2024-08-26 14:42 UTC, PhoebeMitchell commented on unity-ggjj/Assets/Scripts/GameState/InvestigationState.cs
> +                var bgScene = _moveOptions.First(choice => choice.text == valueTuple.text).tags.First(value => value.ToLower() != "move"&& value.ToLower() != "locked");
Another long line.

```suggestion
                var bgScene = _moveOptions
                    .First(choice => choice.text == valueTuple.text)
                    .tags
                        .First(value => 
                            value.ToLower() != "move"&&
                            value.ToLower() != "locked");
                
```

2024-08-26 14:42 UTC, PhoebeMitchell commented on unity-ggjj/Assets/Scripts/GameState/InvestigationState.cs
> +                var rootPrefab = Resources.Load<GameObject>($"BGScenes/{bgScene}");
Hmm, ideally this should be loaded in the preloading system... we have but I understand if that's too much for this PR

2024-08-26 14:42 UTC, PhoebeMitchell commented on unity-ggjj/Assets/Scripts/GameState/InvestigationState.cs
> +                InvestigationMoveMenu.transform.parent.Find("SceneImage").GetComponent<Image>().sprite = sprite;
Very much would prefer to avoid Find based methods where possible. The object that's loaded should have a reference to these.

2024-08-26 14:42 UTC, PhoebeMitchell commented on unity-ggjj/Assets/Scripts/GameState/NarrativeGameState.cs
> +using UnityEngine.Serialization;
Unused using

```suggestion
```

2024-08-26 14:42 UTC, PhoebeMitchell commented on unity-ggjj/Assets/Scripts/Menu/ChoiceMenu/ChoiceMenu.cs
> +    private void InitialiseCoroutine(List<Choice> choiceList)
What's the reason for reverting this? Is the problem outlined in the comment fixed some other way (which would be super btw)? If so, this is no longer a coroutine and should be renamed, and having this logic extracted into it's own method becomes a little redundant.

Otherwise this change should be reverted.

2024-08-26 14:42 UTC, PhoebeMitchell commented on unity-ggjj/Assets/Tests/PlayModeTests/Suites/Scripts/InvestigationState/InvestigationStateKeyboardTests.cs
> +        private IEnumerator PressRight()
```suggestion
        }
        
        private IEnumerator PressRight()
```

2024-08-26 14:42 UTC, PhoebeMitchell commented on unity-ggjj/Assets/Tests/PlayModeTests/Suites/Scripts/InvestigationState/InvestigationStateKeyboardTests.cs
> +        private IEnumerator PressUp()
```suggestion
        }
        
        private IEnumerator PressUp()
```

2024-08-26 14:42 UTC, PhoebeMitchell commented on unity-ggjj/Assets/Tests/PlayModeTests/Suites/Scripts/InvestigationState/InvestigationStateKeyboardTests.cs
> +        private IEnumerator PressDown()
```suggestion
        }
        
        private IEnumerator PressDown()
```

2024-08-26 14:42 UTC, PhoebeMitchell commented on unity-ggjj/Assets/Tests/PlayModeTests/Suites/Scripts/InvestigationState/InvestigationStateMouseTests.cs
> +// using System.Collections;
This file supposed to be all commented?

2024-08-26 14:42 UTC, PhoebeMitchell commented on unity-ggjj/Assets/Tests/PlayModeTests/Suites/Scripts/InvestigationState/InvestigationStateTest.cs
> +        }
For the record, when I tried updating the input system a lot of the tests were fixed by moving the StoryProgresser setup to the UnitySetUp method. Not sure why, but maybe because [UnitySetUp is called before SetUp](https://docs.unity3d.com/Packages/com.unity.test-framework@1.1/manual/reference-unitysetup-and-unityteardown.html).

Though it didn't fix inputs just not being registered 💀 

Anyhow, might be a good idea to move it to the beginning of the UnitySetUp method anyway. Not much reason for it to be here on it's own.

2024-08-26 14:42 UTC, PhoebeMitchell commented on unity-ggjj/Assets/Tests/PlayModeTests/TestScripts/InvestigationUI.ink
> +=== Dad ===
👨💋

2024-08-27 16:25 UTC, ViMaSter commented on docs/constants.md
> +  - INVESTIGATIONTESTFAIL2
The fail state inside `&MODE:Investigation` will play when presenting irrelevant evidence. It's not implemented yet, but I've added them so I can use them when implementing it.

2024-08-27 16:27 UTC, ViMaSter commented on unity-ggjj/Assets/Scripts/GameState/InvestigationState.cs
> +    [SerializeField] private ChoiceMenu InvestigationMoveMenu;
I've applied these, but to avoid sticking around with `[FormerlySerializedAs(…)]` forever, I've forced Unity to reserialize all assets. This changed almost all `.meta` files, but they are safe to ignore.

2024-08-27 16:30 UTC, ViMaSter commented on unity-ggjj/Assets/Tests/PlayModeTests/Suites/Scripts/InvestigationState/InvestigationStateMouseTests.cs
> +// using System.Collections;
Nope, I just forgot to fill it out after the keyboard tests took care of coverage. 🫠 

I have removed them and will add them as part of the next PR for this issue, just so I don't keep this PR open for too long. Does that work for you too?

2024-08-27 16:31 UTC, ViMaSter commented on unity-ggjj/Assets/Tests/PlayModeTests/Suites/Scripts/InvestigationState/InvestigationStateTest.cs
> +        }
Resolved in 6eed7e2503fe39a43aca92b7b8086db8b0b397c2.

2024-08-27 16:32 UTC, ViMaSter commented on docs/methods/Progression.md
> +  - `&UNLOCK_CHOICE:Nice Coat,Talk`
If that works for you too, I'll make that a conversation in the next review meeting and would integrate it as-is for now?

2024-08-27 16:33 UTC, ViMaSter commented on unity-ggjj/Assets/Scripts/GameState/InvestigationState.cs
> +    private readonly List<string> _examinedChoices = new();
Bingo. Removed in https://github.com/Studio-Lovelies/GG-JointJustice-Unity/pull/460/commits/c7b57d13a43a3b4afc6a4d87d5ded3b99a51a5d2.

2024-08-27 16:36 UTC, ViMaSter commented on unity-ggjj/Assets/Scripts/Menu/ChoiceMenu/ChoiceMenu.cs
> +    private void InitialiseCoroutine(List<Choice> choiceList)
I couldn't find any scenario where this became an issue and all automated tests pass. 👀 

I've inlined the method in 29bd9f82e5ec422cb3ddbe6fe23767f8f11c6618.

2024-08-27 16:37 UTC, PhoebeMitchell commented on docs/methods/Progression.md
> +  - `&UNLOCK_CHOICE:Nice Coat,Talk`
That's fine with me. Ultimately it's the writers who are using this 👍

2024-08-27 16:39 UTC, ViMaSter commented on unity-ggjj/Assets/Scripts/GameState/InvestigationState.cs
> +        var selectableAndLabel = InvestigationMoveMenu.transform.GetComponentsInChildren<MenuItem>().Select(menuItem => (menuItem, menuItem.GetComponentInChildren<TextMeshProUGUI>().text)).ToList();
Replaced in 4e0352c2e15093b063cff7951828703428d11c48.

2024-08-27 16:41 UTC, ViMaSter commented on unity-ggjj/Assets/Scripts/GameState/InvestigationState.cs
> +                InvestigationMoveMenu.transform.parent.Find("SceneImage").GetComponent<Image>().sprite = sprite;
Since we're not sure that's how we want preview images to work anyway (it's just a first pass of this game feature), I'd add a note to the issue to revisit this as soon as we know how we want preview images to work and leave it in for now? (We might use normal Sprites instead of Scenes instead…)

2024-08-27 16:42 UTC, ViMaSter commented on unity-ggjj/Assets/Scripts/GameState/InvestigationState.cs
> +                var rootPrefab = Resources.Load<GameObject>($"BGScenes/{bgScene}");
That's a really great idea actually, but I also see a bit of scope creep here. Would you be alright with me revisiting this in the next PR for this feature?

2024-08-27 17:37 UTC, PhoebeMitchell approved these changes
This is good. Be sure to make a note of the things are need refactoring at some point.

2024-08-27 17:37 UTC, PhoebeMitchell commented on unity-ggjj/Assets/Scripts/GameState/InvestigationState.cs
> +                _investigationMoveMenu.transform.parent.Find("SceneImage").GetComponent<Image>().sprite = sprite;
Not fully happy with this because of find and string dependency but it feels like the most simple solution for now to be honest.

2024-08-28 12:59 UTC, ViMaSter commented
@PhoebeMitchell Feel free to give this another look; merging the assets was a bit convoluted, so make sure these three changes still work in my branch, otherwise we might accidentally lose them by integrating this PR:
![image](https://github.com/user-attachments/assets/b263eb4c-8e82-4896-9c7a-72163eeb6f72)

Also added all changes I opted not to include in this PR to https://github.com/Studio-Lovelies/GG-JointJustice-Unity/issues/456#issuecomment-2315246456. Let me know if I've missed anything!

2024-08-28 13:00 UTC, ViMaSter commented on unity-ggjj/Assets/Scripts/GameState/InvestigationState.cs
> +                InvestigationMoveMenu.transform.parent.Find("SceneImage").GetComponent<Image>().sprite = sprite;
Natsumi and Koda couldn't think of any case where we might need custom images, so I added refactoring this to https://github.com/Studio-Lovelies/GG-JointJustice-Unity/issues/456#issuecomment-2315246456.

2024-08-28 13:02 UTC, ViMaSter commented on unity-ggjj/Assets/Scripts/GameState/InvestigationState.cs
> +                _investigationMoveMenu.transform.parent.Find("SceneImage").GetComponent<Image>().sprite = sprite;
Agreed. Added [a list of work left on the issue](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/issues/456#issuecomment-2315246456) which tracks that as well.

2024-08-28 13:32 UTC, merged