Feature/13 player can access the evidence menu
Studio-Lovelies/GG-JointJustice-Unity pull request #48
Opened 2021-09-04 21:04 UTC by TooManyMoths

## Summary

Adds functionality to open the evidence menu. Evidence menu can be toggled by pressing Z or calling the PRESENT_EVIDENCE action (which will make it so the menu cannot be closed). The evidence menu uses assets already in the project, and its design is not final.

The Evidence scriptable object is used to handle individual evidence. The EvidenceDictionary scriptable object is used to store multiple pieces of evidence. EvidenceDictionaries can be assigned to the EvidenceController to dictate what evidence is available in a scene. Selecting a piece of evidence calls the OnEvidenceClicked event on EvidenceMenu. Currently it is hooked up to closing the menu and continuing the story, but should be used to pass the selected Evidence object to whatever is going to handle presenting of evidence.

## Before/after screenshots and/or animated gif
![evidencedemo2](https://user-images.githubusercontent.com/67964179/132107825-0f037c55-5740-4cd1-a703-d7866f608324.gif)
The GIF above demonstrates the evidence menu opening when calling the PRESENT_EVIDENCE command, opening and closing the menu with the Z button, adding to the evidence menu with the ADD_EVIDENCE command, removing it with the REMOVE_EVIDENCE command, and swapping it with alternate evidence using the SUBSTITUTE_EVIDENCE command.

## Testing instructions

Open the "Actor Animator - Test Scene" scene (or any scene with the standard inclusion, using the "EvidenceAddingTestScript" narrative script) and enter play mode. Press Z to open the evidence menu when the dialogue controller is not busy. Press X or Enter to progress through dialog. When an evidence menu opens, navigate with the arrow keys and choose a piece of evidence to present with Enter.

## Additional information

- `[x]` Changes UI
- `[x]` Introduces new feature
- `[ ]` Removes existing feature
- `[x]` Has associated resource: 
  
#13

2021-09-04 21:34 UTC, lyndsiWilliams submitted a review, later dismissed
Just one missing summary, this PR looks great!

2021-09-04 21:34 UTC, lyndsiWilliams commented on Assets/Scripts/TextDecoder/DialogueController.cs
> +    public void SetMenuOpen(bool isMenuOpen)
✨ This method is missing a summary ✨

2021-09-04 21:47 UTC, notexplosive approved these changes, later dismissed
This is really good stuff! A few notes about error logging and some naming nitpicks.

2021-09-04 21:47 UTC, notexplosive commented on Assets/Scripts/Evidence/EvidenceDictionary.cs
> +        if (_evidenceList == null)
Is there any time this wouldn't be true? (ditto for the null check below)

2021-09-04 21:47 UTC, notexplosive commented on Assets/Scripts/Evidence/EvidenceMenu.cs
> +        _currentPage %= _numberOfPages;
Is it safe to do a `%` on a negative number? Every language handles modulus differently.

2021-09-04 21:47 UTC, notexplosive commented on Assets/Scripts/Evidence/EvidenceDictionary.cs
> +            return;
Maybe log an error before the return?

2021-09-04 21:47 UTC, notexplosive commented on Assets/Scripts/Evidence/EvidenceDictionary.cs
> +    public Evidence GetEvidence(string evidence)
nit: parameter name should be `evidenceName` (there are a few other examples of this but I'm not gonna crowd my review with them)

2021-09-04 21:47 UTC, notexplosive commented on Assets/Scripts/Evidence/EvidenceMenu.cs
> +            button.interactable = !(_numberOfPages < 2); // Navigation buttons not needed if less than 2 pages
nit: replace `!(_numberOfPages < 2)` with `numberOfPages > 1` (I think I did that right?)

2021-09-04 21:47 UTC, notexplosive commented on Assets/Scripts/Evidence/EvidenceDictionary.cs
> +        }
Maybe _also_ log an error if the AltEvidence was null. Better than failing silently.

2021-09-04 21:47 UTC, notexplosive commented on Assets/Scripts/EvidenceController.cs
> +        _currentEvidenceDictionary.AddEvidence(_masterEvidenceDictionary.GetEvidence(evidence));
Error check for if the master dictionary is missing the item? Right now it'll throw an exception, but maybe we could get a slightly more helpful error.

2021-09-04 21:47 UTC, notexplosive commented on Assets/Scripts/EvidenceController.cs
> +    public void SubstituteEvidence(string evidence)
nit: name should be `SubstituteEvidenceWithAlt`

2021-09-04 21:59 UTC, JuiceGrape requested changes
Looks great, but I have some concerns about the evidence controller. Feel free to contact me to discuss or apply my requested changes. I'll check again after you've done either.

2021-09-04 21:59 UTC, JuiceGrape commented on Assets/Scripts/Evidence/EvidenceDictionary.cs
> +    private Dictionary<string, Evidence> _evidenceDictionary;
Isn't this kinda overkill? I can't imagine making a new scriptable object for every scene. I'd rather this be a script we can just add into the scene as a game object

2021-09-04 21:59 UTC, JuiceGrape commented on Assets/Scripts/Evidence/EvidenceDictionary.cs
> +    private bool CheckIfEvidenceInDictionary(string evidence)
Function name is inaccurate, should be IsEvidenceInDictionary as you're also returning the value, not just checking it

2021-09-04 21:59 UTC, JuiceGrape commented on Assets/Scripts/Evidence/EvidenceDictionary.cs
> +    private Dictionary<string, Evidence> _evidenceDictionary;
This is also much too complicated for a scriptable object, so I'm gonna suggest you turn this into a regular MonoBehaviour

2021-09-04 21:59 UTC, JuiceGrape commented on Assets/Scripts/Evidence/EvidenceDictionary.cs
> +        if (_evidenceList != null && (_evidenceDictionary == null || _evidenceDictionary.Count != _evidenceList.Count))
Why is your entire dictionary replaced every time the object gets enabled? Probably shouldn't happen

2021-09-04 21:59 UTC, JuiceGrape commented on Assets/Scripts/Evidence/EvidenceDictionary.cs
> +            _evidenceDictionary = new Dictionary<string, Evidence>();
You already create this in OnEnable, not necessary.

2021-09-04 21:59 UTC, JuiceGrape commented on Assets/Scripts/Evidence/EvidenceDictionary.cs
> +            _evidenceList = new List<Evidence>();
Serialized fields never need a "new"

2021-09-04 21:59 UTC, JuiceGrape commented on Assets/Scripts/EvidenceController.cs
> +    [SerializeField] private UnityEvent _onPresentEvidence;
Please provide a string name of the evidence or the evidence object itself with the event. Either works

2021-09-04 21:59 UTC, JuiceGrape commented on Assets/Scripts/EvidenceController.cs
> +        _currentEvidenceDictionary.AddEvidence(_masterEvidenceDictionary.GetEvidence(evidence));
Try catch into a log maybe?

2021-09-04 21:59 UTC, JuiceGrape commented on Assets/Scripts/Menu/MenuItem.cs
>          if (!TryGetComponent(out _highlight))
I know it's not part of this code, but I know you wrote it so: This should probably have targeted <> brackets

2021-09-04 21:59 UTC, JuiceGrape commented on Assets/Scripts/Menu/MenuOpener.cs
> +        if (_parentMenu == _menuToOpen)
Doesn't GetComponentInParent return null if it cannot find anything? It should never find itself at the least

2021-09-04 21:59 UTC, JuiceGrape commented on Assets/Scripts/Menu/MenuOpener.cs
> +    public void ToggleMenu()
Kudos: Good function to add, keeping the logic contained.
Close convo when read

2021-09-04 21:59 UTC, JuiceGrape commented on Assets/Scripts/Menu/MenuOpener.cs
> +        StartCoroutine(CanCloseDelay());
What's the problem with being able to close it on the same frame? Is the function being called multiple times in a single frame? If so, that could be a problem with the input logic class instead

2021-09-04 21:59 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/DialogueController.cs
> +        if (_isBusy || _isMenuOpen)
Kudos: Good way to add this
Close convo after reading

2021-09-04 22:27 UTC, JuiceGrape commented on Assets/Scripts/Evidence/EvidenceMenu.cs
> +    private UnityEvent<Evidence> _onEvidenceClicked;
I would prefer it if this event lived in the evidence controller. Could you move it there? (seeing as you already have a reference to it)

2021-09-04 22:30 UTC, JuiceGrape commented on Assets/Scripts/Evidence/EvidenceMenu.cs
> +        _currentPage %= _numberOfPages;
I'd say yes as it's working

2021-09-05 00:40 UTC, TooManyMoths commented on Assets/Scripts/TextDecoder/DialogueController.cs
> +    public void SetMenuOpen(bool isMenuOpen)
Added

2021-09-05 00:41 UTC, TooManyMoths commented on Assets/Scripts/Evidence/EvidenceDictionary.cs
> +        if (_evidenceList == null)
Method removed in latest push.

2021-09-05 00:43 UTC, TooManyMoths commented on Assets/Scripts/Evidence/EvidenceDictionary.cs
> +            return;
Error logging is handled in the CheckIfEvidenceInDictionary (now IsEvidenceInDictionary) method.

2021-09-05 00:45 UTC, TooManyMoths commented on Assets/Scripts/Evidence/EvidenceMenu.cs
> +            button.interactable = !(_numberOfPages < 2); // Navigation buttons not needed if less than 2 pages
Done

2021-09-05 00:53 UTC, TooManyMoths commented on Assets/Scripts/Evidence/EvidenceMenu.cs
> +        _currentPage %= _numberOfPages;
The _currentPage += _numberOfPages - 1 line should keep it positive, but I've added a check if the number of pages is less than one.

2021-09-05 00:54 UTC, TooManyMoths commented on Assets/Scripts/Evidence/EvidenceDictionary.cs
> +        }
Done

2021-09-05 00:57 UTC, TooManyMoths commented on Assets/Scripts/Evidence/EvidenceDictionary.cs
> +    public Evidence GetEvidence(string evidence)
Should all be changed but feel free to point out any I've missed.

2021-09-05 01:02 UTC, TooManyMoths commented on Assets/Scripts/EvidenceController.cs
> +        _currentEvidenceDictionary.AddEvidence(_masterEvidenceDictionary.GetEvidence(evidence));
This is now handled by the EvidenceDictionary monobehaviour which checks if the evidence is in the master dictionary or is already in the current dictionary when adding evidence.

2021-09-05 01:14 UTC, TooManyMoths commented on Assets/Scripts/EvidenceController.cs
> +    public void SubstituteEvidence(string evidence)
Changed

2021-09-05 01:22 UTC, TooManyMoths commented on Assets/Scripts/Evidence/EvidenceDictionary.cs
> +    private Dictionary<string, Evidence> _evidenceDictionary;
Split this into an EvidenceDictionary monobehaviour that handles conversion to a dictionary and getting adding and removing evidence, and an EvidenceList scriptable object that can be used to define available evidence in a scene. Evidence at the start of the scene can be assigned to the monobehaviour.

2021-09-05 01:22 UTC, TooManyMoths commented on Assets/Scripts/Evidence/EvidenceDictionary.cs
> +        if (_evidenceList != null && (_evidenceDictionary == null || _evidenceDictionary.Count != _evidenceList.Count))
Dictionary is now created on Awake in a monobehaviour.

2021-09-05 01:23 UTC, TooManyMoths commented on Assets/Scripts/Evidence/EvidenceDictionary.cs
> +    private bool CheckIfEvidenceInDictionary(string evidence)
Changed to IsEvidenceInDictionary

2021-09-05 01:23 UTC, TooManyMoths commented on Assets/Scripts/Evidence/EvidenceDictionary.cs
> +            _evidenceDictionary = new Dictionary<string, Evidence>();
This method has been removed in latest push.

2021-09-05 01:25 UTC, TooManyMoths commented on Assets/Scripts/Evidence/EvidenceDictionary.cs
> +            _evidenceList = new List<Evidence>();
This was for when a new object was created if no object was already assigned. The list needed to be initialised. Nevertheless this has been removed in latest push in favour of the monobehaviour approach.

2021-09-05 01:29 UTC, TooManyMoths commented on Assets/Scripts/EvidenceController.cs
> +    [SerializeField] private UnityEvent _onPresentEvidence;
Event is called when the PRESENT_EVIDENCE action is called. Name was confusing. Changed to _onEvidenceMenuOpened.

2021-09-05 01:31 UTC, TooManyMoths commented on Assets/Scripts/Menu/MenuItem.cs
>          if (!TryGetComponent(out _highlight))
Technically redundant but added for readability.

2021-09-05 01:43 UTC, TooManyMoths commented on Assets/Scripts/Menu/MenuOpener.cs
> +        if (_parentMenu == _menuToOpen)
According to unity docs it does search the game object it is on. "Self" is perhaps not accurate as it actually opens the menu this monobehaviour is part of. Updated comment to reflect this and removed reference to line number.

2021-09-05 02:12 UTC, TooManyMoths commented on Assets/Scripts/Menu/MenuOpener.cs
> +        StartCoroutine(CanCloseDelay());
It's because both continue dialogue and select evidence are bound to enter, so when theres a "present evidence" action after continuing dialog it will open the menu on the same frame you press enter and instantly select evidence. This was the only workaround I could think of short of just not having these bound to the same key.

2021-09-05 02:31 UTC, TooManyMoths commented on Assets/Scripts/Evidence/EvidenceMenu.cs
> +    private UnityEvent<Evidence> _onEvidenceClicked;
Done

2021-09-05 21:52 UTC, JuiceGrape approved these changes
Large scale changes look to be implemented, I'll trust you with the rest

2021-09-05 22:00 UTC, JuiceGrape commented on Assets/Scripts/Menu/MenuOpener.cs
> +        StartCoroutine(CanCloseDelay());
but why would there ever be one instantly ever? That's not going to happen

2021-09-06 16:49 UTC, lyndsiWilliams approved these changes
Lookin' shiny! This is great! ✨

2021-09-06 16:51 UTC, merged