Player can access the profile menu
Studio-Lovelies/GG-JointJustice-Unity pull request #52
Opened 2021-09-11 03:42 UTC by TooManyMoths

## Summary

Updates the evidence menu to support showing profiles. Actor dictionaries now use the same system as evidence (dictionary created on a monobehaviour instead of in the scriptable object). The logic from EvidenceDictionary is now in its own class called ObjectDictionary which the ActorDictionary and EvidenceDictionary monobehaviours use. ActorData and Evidence now implement ICourtRecordObject which allows their names, icons, and descriptions to be accessed. Also features tests for the evidence menu and ObjectDictionary class.

## Before/after screenshots and/or animated gif

![profilesdemo2](https://user-images.githubusercontent.com/67964179/132934810-b9e0b182-6462-4ef6-8edf-f42d955261bf.gif)

## Testing instructions

Open a scene with the StandardInclusion asset and enter play mode. Press z to open the evidence menu, then press c to open the profiles menu. Navigate with the arrow keys (and check for spelling mistakes in each bio).
Open the unity test runner and run the play mode and edit mode tests.

## Additional information

- `[x]` Changes UI
- `[x]` Introduces new feature
- `[ ]` Removes existing feature
- `[x]` Has associated resource: 
  
#11

2021-09-12 12:32 UTC, JuiceGrape approved these changes, later dismissed
Great work! Feel free to close the kudos comments when read

2021-09-12 12:32 UTC, JuiceGrape commented on Assets/Scripts/Actor/ActorDictionary.cs
> +public class ActorDictionary : ObjectDictionaryInterface<ActorData, ActorList>, ICourtRecordObjectDictionary
Kudos: Nice one! Sexy ass implementation, shit like this makes me happy

2021-09-12 12:32 UTC, JuiceGrape commented on Assets/Scripts/Actor/ActorData.cs
> +        switch (_ageCertainty)
For extendability it is better to leave the default as an error and then handle all known cases in the switch. Also handling the default in the switch is better practice for this reason, so when a new enum gets added and they forget to extend this switch, it is instantly noticeable

2021-09-12 12:32 UTC, JuiceGrape commented on Assets/Scripts/Evidence/EvidenceDictionary.cs
> +public class EvidenceDictionary : ObjectDictionaryInterface<Evidence, EvidenceList>, ICourtRecordObjectDictionary
Kudos: New implementation looks much cleaner

2021-09-12 16:59 UTC, ViMaSter commented on Assets/Tests/PlayModeTests/Scripts/EvidenceMenu/EvidenceMenuMouseTests.cs
> +        // [UnityTest, Order(1)]
This test appears to be commented out and doesn't show up on the Test Runner. I'd suggest either remove the code for it or integrating it somehow!

2021-09-12 17:00 UTC, ViMaSter commented on Assets/Tests/PlayModeTests/Scripts/EvidenceMenu/EvidenceMenuMouseTests.cs
> +using TMPro;
This namespace seems to be unused in this file. I'd suggest removing it.

2021-09-12 17:02 UTC, ViMaSter commented on Assets/Tests/PlayModeTests/Scripts/EvidenceMenu/EvidenceMenuMouseTests.cs
> +                MenuItem menuItem = menuItems.First(menuItem => menuItem.gameObject.name == $"EvidenceMenuItem ({i})");
Nit: Having the outer variable (`MenuItem menuItem`) **and** parameter of the `First()`-predicate (.First(menuItem`) is a bit confusing to read for me and also prevents the variable from being used inside the scope. I'd suggest renaming either the inner or outer variable.

2021-09-12 17:03 UTC, ViMaSter commented on Assets/Tests/PlayModeTests/Scripts/EvidenceMenu/EvidenceMenuKeyboardTests.cs
> +                evidenceTextBoxes.First(evidenceTextBoxe => evidenceTextBoxe.gameObject.name == "EvidenceName");
Nit: Typo `evidenceTextBoxe` -> `evidenceTextBox`.

2021-09-12 17:03 UTC, ViMaSter commented on Assets/Tests/PlayModeTests/Scripts/EvidenceMenu/EvidenceMenuKeyboardTests.cs
> +                evidenceTextBoxes.First(evidenceTextBoxe => evidenceTextBoxe.gameObject.name == "EvidenceName");
Nit: Typo `evidenceTextBoxe` -> `evidenceTextBox`.

2021-09-12 17:04 UTC, ViMaSter commented on Assets/Tests/PlayModeTests/Tools/InputTestTools.cs
> +using UnityEngine.UI;
This namespace seems to be unused in this file. I'd suggest removing it.

2021-09-12 19:20 UTC, ViMaSter requested changes
Really solid implementation! Always great to see a bunch of tests being added as well! <3

My only required changes (anything that's not prefixed with `Nit:` or got a 👍) would be:
- the typos ([1](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/pull/52/files#r706865549), [2](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/pull/52/files#r706865542)) and
- [the test case that's commented out](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/pull/52/files#r706865061)

---

A sidenote:

I noticed, that the class `ObjectDictionary` does not implement `IDictionary` and the `ObjectDictionaryInterface` is actually an `abstract class` instead of an `interface`.  
This made this change a bit difficult to read for me initially.  

Looking through the source it definitely is possible to get an understanding of what these classes actually do, but as the terms `interface` and `dictionary` are already being used for definitions inside the language-standard, my mind immediately jumped to a set of behaviors and available methods that aren't actually present inside these classes when initially looking at these classes, which might cause confusion for people working on it the first time or after a long period of time has passed.

If I can offer two suggestions:
1. From what I can see, `ObjectDictionary` is only ever used inside `ObjectDictionaryInterface` and it's test suite. I'd recommend the following approach:
   * Integrate the logic of `ObjectDictionary` into `ObjectDictionaryInterface` making it one class
   * Rename this new `ObjectDictionaryInterface` class to `ObjectDictionary`
   This will result in less nesting of classes, while also reducing potential confusion caused by the word `Interface`
2. Instead of creating and implementing the custom interface `IObjectList`, implement `IDictionary<>` directly
   This will result in associations with the word `Dictionary` actually being fulfilled
   _Note: The same also applies to `ICourtRecordObjectDictionary`._

I'd be happy to hear your thoughts on that; as it's a bigger topic I'm also open to have a quick voice chat about it! However, as the functionallity operates just fine, this is just a suggestion and not blocking approval!

---

I really appreciate you adhering to the boyscout principle of "leaving the campsite cleaner than you found it" and taking the time to create the `InputTestTools` class! This should keep flakey tests to an absolute minimum!

2021-09-12 19:20 UTC, ViMaSter commented on Assets/Tests/PlayModeTests/Tools/InputTestTools.cs
> +        public IEnumerator RepeatPressForSeconds(ButtonControl control, float seconds, int repeats)
Nit: `RepeatPressForSeconds()` seems to be unused. I'd personally suggest either removing it (if we end up needing it, we can add it later) or merging it with `PressForSeconds()` by adding `repeats` as an optional parameter (`public IEnumerator PressForSeconds(ButtonControl control, float seconds, int repeats = 1)`).  
I'm always a big fan of removing unused code, that way there's less of it to keep in mind when working with it!

2021-09-12 19:20 UTC, ViMaSter commented on Assets/Tests/PlayModeTests/Tools/InputTestTools.cs
> +    public class InputTestTools : InputTestFixture
Wrapping this functionality in a helper-class is a really solid addition! Always a big fan of the [rule of 3](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming))! 👍

2021-09-12 19:20 UTC, ViMaSter commented on Assets/Tests/EditModeTests/ObjectDictionaryTests.cs
> +    }
Nit: These methods can be made `static` and return `IEnumerable<>` instead of `List<>`.

2021-09-12 19:20 UTC, ViMaSter commented on Assets/Tests/EditModeTests/ObjectDictionaryTests.cs
> +        }
Nit: The `*Count` variables and `numberOfObjectsToRemove` used during setup of each of these cases can be made `const`, to prevent them from being accidentally changed during runtime.

2021-09-12 19:20 UTC, ViMaSter commented on Assets/Scripts/TextDecoder/DialogueController.cs
> +    public void HandlePresenting(ICourtRecordObject presentedObject)
Really intuitive way of simplifying the public interface of this class while making it even less error-prone! 👍

2021-09-12 19:20 UTC, ViMaSter commented on Assets/Scripts/ObjectDictionary/ObjectDictionaryInterface.cs
> +/// <typeparam name="T">The type of object to store in the dictionary.</typeparam>
Nit: I personally find specifying `The type of values in the dictionary.` to make it easier to read, as only the value type is being set.

2021-09-12 19:20 UTC, ViMaSter commented on Assets/Scripts/ObjectDictionary/ObjectDictionaryInterface.cs
> +    protected T[] CurrentObjectList { get; private set; }
Nit: The tooltips speak of `actors` and `evidence` explicitly, while the fields are technically being abstract. I'd change this to `ICourtRecordObject` or `Object` instead.

2021-09-12 19:20 UTC, ViMaSter commented on Assets/Scripts/ObjectDictionary/ObjectDictionaryInterface.cs
> +    private S _masterObjectList;
Nit: The term `master` is immediately associated with a `master/slave`-relationship (think SATA, IDE, databases), which doesn't really apply here. Similarly to the tooltip-text, I'd prefer `availableObjectList`, as it contains a list of all potential objects that can be added to the `CurrentObjectList`.

2021-09-12 19:20 UTC, ViMaSter commented on Assets/Scripts/ObjectDictionary/ObjectDictionaryInterface.cs
> +    public T GetObjectAtIndex(int index)
Nit: This method is never used. `GetObjectAtIndex()` is only ever used on `ICourtRecordObjectDictionary`-objects, which - as it's an interface - require an explicit implementation and - as it exists as a shallower type - can't fall back to this base implementation. I'd personally suggest removing it.

2021-09-12 19:20 UTC, ViMaSter commented on Assets/Scripts/ObjectDictionary/IObjectList.cs
> +public interface IObjectList<T> where T : Object
Nit: I'd suggest using `<out T>` instead of `<T>` here, which would make this [a covariant](https://docs.microsoft.com/en-us/dotnet/standard/generics/covariance-and-contravariance#generic-interfaces-with-covariant-type-parameters), allowing it to be used more broadly.

2021-09-12 19:20 UTC, ViMaSter commented on Assets/Scripts/ObjectDictionary/ICourtRecordObject.cs
> +    public string name { get; }
Nit: This might be something Unity-specific related to `name` I'm unaware of, but all other properties in this interface start with an uppercase letter, so I'd personally prefer aligning them to all use UpperCamelCase.

2021-09-12 19:20 UTC, ViMaSter commented on Assets/Scripts/Evidence/EvidenceMenu.cs
>  }
Nit: Strictly not part of this PR, but the `System` namespace in this file seems to be unused. I'd suggest removing it.

2021-09-12 19:20 UTC, ViMaSter commented on Assets/Scripts/Actor/ActorData.cs
> +        switch (_ageCertainty)
Agreed! `AgeCertainty.Unknown` is a valid state and should be handled appropriately. The `default` should be treated as an exception or error.

---

I'd personally also suggest converting it to a [switch expression](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/switch-expression) like so:
```cs
string age = _ageCertainty switch {
    AgeCertainty.Known => Age.ToString(),
    AgeCertainty.Guess => $"Maybe {Age}?",
    AgeCertainty.Unknown => "???",
    _ => throw new ArgumentOutOfRangeException()
};
```

2021-09-12 19:20 UTC, ViMaSter commented on Assets/Scripts/ObjectDictionary/ObjectDictionary.cs
> +    private Dictionary<string, T> ArrayToDictionary(IEnumerable<T> array)
Nit: I'd recommend making this method `static` as it doesn't appear to be using any instance members.

2021-09-13 06:25 UTC, TooManyMoths commented on Assets/Scripts/Actor/ActorData.cs
> +        switch (_ageCertainty)
Changed to use ViMaSter's suggestion.

2021-09-13 06:27 UTC, TooManyMoths commented on Assets/Tests/PlayModeTests/Scripts/EvidenceMenu/EvidenceMenuMouseTests.cs
> +        // [UnityTest, Order(1)]
Good catch! Commented out that method for debugging purposes and must have missed the attributes when uncommenting. Fixed.

2021-09-13 06:28 UTC, TooManyMoths commented on Assets/Tests/PlayModeTests/Scripts/EvidenceMenu/EvidenceMenuMouseTests.cs
> +using TMPro;
Done

2021-09-13 06:30 UTC, TooManyMoths commented on Assets/Tests/PlayModeTests/Scripts/EvidenceMenu/EvidenceMenuMouseTests.cs
> +                MenuItem menuItem = menuItems.First(menuItem => menuItem.gameObject.name == $"EvidenceMenuItem ({i})");
Changed First() parameter to "item".

2021-09-13 06:30 UTC, TooManyMoths commented on Assets/Tests/PlayModeTests/Scripts/EvidenceMenu/EvidenceMenuKeyboardTests.cs
> +                evidenceTextBoxes.First(evidenceTextBoxe => evidenceTextBoxe.gameObject.name == "EvidenceName");
Fixed

2021-09-13 06:31 UTC, TooManyMoths commented on Assets/Tests/PlayModeTests/Tools/InputTestTools.cs
> +using UnityEngine.UI;
Done

2021-09-13 06:41 UTC, TooManyMoths commented on Assets/Scripts/ObjectDictionary/ObjectDictionaryInterface.cs
> +/// <typeparam name="T">The type of object to store in the dictionary.</typeparam>
Changed

2021-09-13 06:44 UTC, TooManyMoths commented on Assets/Scripts/ObjectDictionary/ObjectDictionaryInterface.cs
> +    private S _masterObjectList;
Changed to _availableObjectList

2021-09-13 06:46 UTC, TooManyMoths commented on Assets/Scripts/ObjectDictionary/IObjectList.cs
> +public interface IObjectList<T> where T : Object
Done

2021-09-13 06:47 UTC, TooManyMoths commented on Assets/Scripts/Evidence/EvidenceMenu.cs
>  }
Done

2021-09-13 06:48 UTC, TooManyMoths commented on Assets/Scripts/ObjectDictionary/ObjectDictionary.cs
> +    private Dictionary<string, T> ArrayToDictionary(IEnumerable<T> array)
Done

2021-09-13 06:52 UTC, TooManyMoths commented on Assets/Scripts/ObjectDictionary/ICourtRecordObject.cs
> +    public string name { get; }
This is to allow the name property of Object to be accessed. Would you suggest changing it to Name and then doing `string Name => name;` on classes that implement this instead?

2021-09-13 06:58 UTC, TooManyMoths commented on Assets/Scripts/ObjectDictionary/ObjectDictionaryInterface.cs
> +    protected T[] CurrentObjectList { get; private set; }
Remnants of old implementations. Updated.

2021-09-13 07:02 UTC, TooManyMoths commented on Assets/Tests/EditModeTests/ObjectDictionaryTests.cs
> +    }
Done

2021-09-13 07:07 UTC, TooManyMoths commented on Assets/Tests/PlayModeTests/Tools/InputTestTools.cs
> +        public IEnumerator RepeatPressForSeconds(ButtonControl control, float seconds, int repeats)
Removed "Repeat" methods. Modified PressForFrame and PressForSeconds to allow repeats.

2021-09-13 07:07 UTC, TooManyMoths commented on Assets/Tests/EditModeTests/ObjectDictionaryTests.cs
> +        }
Done

2021-09-13 10:34 UTC, TooManyMoths commented on Assets/Tests/PlayModeTests/Scripts/EvidenceMenu/EvidenceMenuKeyboardTests.cs
> +                evidenceTextBoxes.First(evidenceTextBoxe => evidenceTextBoxe.gameObject.name == "EvidenceName");
Fixed

2021-09-13 10:34 UTC, ViMaSter commented on Assets/Scripts/ObjectDictionary/ICourtRecordObject.cs
> +    public string name { get; }
That actually sounds pretty good!  
The [official docs of `UnityEngine.Object.name`](https://docs.unity3d.com/ScriptReference/Object.html) state that `Components share the same name with the game object and all attached components`. Given that, I'd just go a step further and change it to `DisplayName`. That way this property is distinctly tied to our game and - if we choose to do so - we can use the value from the engine by using `=> name` on any class that derived from `UnityEngine.Object`.

2021-09-13 14:24 UTC, TooManyMoths commented on Assets/Scripts/ObjectDictionary/ICourtRecordObject.cs
> +    public string name { get; }
Changed to InstanceName

2021-09-15 15:17 UTC, JuiceGrape approved these changes, later dismissed

2021-09-15 15:33 UTC, TooManyMoths commented on Assets/Scripts/ObjectDictionary/ObjectDictionaryInterface.cs
> +    public T GetObjectAtIndex(int index)
Removed.

2021-09-15 16:19 UTC, ViMaSter approved these changes, later dismissed
Looks good to me! Just a few nits, but nothing that's worth blocking in my opinion! Oh and thanks for integrating the typo fix for the build artifacts too.

2021-09-15 16:19 UTC, ViMaSter commented on Assets/Tests/PlayModeTests/Scripts/EvidenceMenu/EvidenceMenuKeyboardTests.cs
> +                evidenceTextBoxes.First(evidenceTextBoxe => evidenceTextBoxe.gameObject.name == "EvidenceName");
Just FYI: The latest version of this file still contains the typo. 👀
https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/0bea8fa254d3b558d48947255e17a399e51e4f56/Assets/Tests/PlayModeTests/Scripts/EvidenceMenu/EvidenceMenuKeyboardTests.cs#L131

2021-09-15 16:19 UTC, ViMaSter commented on Assets/Tests/EditModeTests/ObjectDictionaryTests.cs
> +        private string[] _evidenceNames =
Nit: This field can be made `readonly`.

2021-09-15 16:19 UTC, ViMaSter commented on Assets/Tests/EditModeTests/ObjectDictionaryTests.cs
> +using System.Linq;
Nit: No symbols from these namespaces are used in the this file, so the first two lines of this file can safely be removed.

2021-09-15 16:19 UTC, ViMaSter commented on Assets/Scripts/ObjectDictionary/ObjectDictionary.cs
> +    private bool IsObjectInDictionary(string objectName, Dictionary<string, T> dictionaryToCheck)
Nit: This method can be made static.

2021-09-15 16:19 UTC, ViMaSter commented on Assets/Scripts/Evidence/EvidenceDictionary.cs
>  using UnityEngine;
Nit: No symbols from this namespace are used in the this file, so this `using`-directive can safely be removed too.

2021-09-15 16:19 UTC, ViMaSter commented on Assets/Scripts/Actor/ActorList.cs
> +using System.Collections.Generic;
Nit: No symbols from this namespace are used in the this file, so this `using`-directive can safely be removed.

2021-09-15 16:19 UTC, ViMaSter commented on Assets/Scripts/Actor/ActorData.cs
>  using System.Collections.Generic;
Nit: No symbols from this namespace are used in the this file, so this using-directive can safely be removed.

2021-09-15 16:19 UTC, ViMaSter commented on Assets/Scripts/Actor/ActorController.cs
>  using System.Collections.Generic;
Nit: No symbols are used from `using System;` and `using System.Collections;`, so the first two lines of this file can safely be removed.

2021-09-15 16:19 UTC, ViMaSter commented on Assets/Scripts/Actor/ActorData.cs
>      [field: SerializeField, Tooltip("Name displayed when referring to this actor or when they are speaking.")]
Nit: The property `DefaultSprite` isn't used (anymore?), could this be removed until functionality that uses it exists or would this result in a lot of Prefabs having to be updated?

2021-09-15 16:19 UTC, ViMaSter commented on Assets/Scripts/Evidence/Evidence.cs
>  using UnityEngine;
Nit: No symbols are used from `using System;` and `using System.Collections;`, so the first two lines of this file can safely be removed.

2021-09-15 16:19 UTC, ViMaSter commented on Assets/Scripts/Evidence/EvidenceController.cs
>  using System.Collections.Generic;
Nit: No symbols are used from `using System;` and `using System.Collections;`, so the first two lines of this file can safely be removed.

2021-09-15 16:19 UTC, ViMaSter commented on Assets/Scripts/ObjectDictionary/ObjectInventory.cs
> +using System.Collections;
Nit: No symbols from this namespace are used in the this file, so this using-directive can safely be removed.

2021-09-16 08:57 UTC, TooManyMoths commented on Assets/Tests/PlayModeTests/Scripts/EvidenceMenu/EvidenceMenuKeyboardTests.cs
> +                evidenceTextBoxes.First(evidenceTextBoxe => evidenceTextBoxe.gameObject.name == "EvidenceName");
Fixed. Must have come back when reverting back to humble object pattern.

2021-09-16 09:01 UTC, TooManyMoths commented on Assets/Tests/EditModeTests/ObjectDictionaryTests.cs
> +        private string[] _evidenceNames =
File no longer exists.

2021-09-16 09:01 UTC, PhoebeMitchell commented on Assets/Tests/EditModeTests/ObjectDictionaryTests.cs
> +using System.Linq;
File no longer exists.

2021-09-16 09:05 UTC, TooManyMoths commented on Assets/Scripts/ObjectDictionary/ObjectDictionary.cs
> +    private bool IsObjectInDictionary(string objectName, Dictionary<string, T> dictionaryToCheck)
File no longer exists. The version of this method in latest version is public. I'm told static methods are bad in OOP. Thoughts?

2021-09-16 09:06 UTC, TooManyMoths commented on Assets/Scripts/Evidence/EvidenceDictionary.cs
>  using UnityEngine;
File no longer exists.

2021-09-16 09:06 UTC, TooManyMoths commented on Assets/Scripts/Actor/ActorList.cs
> +using System.Collections.Generic;
Outdated.

2021-09-16 09:07 UTC, TooManyMoths commented on Assets/Scripts/Actor/ActorData.cs
>  using System.Collections.Generic;
Removed.

2021-09-16 09:08 UTC, TooManyMoths commented on Assets/Scripts/Actor/ActorController.cs
>  using System.Collections.Generic;
Will leave them to avoid changing too much of a file that isn't explicitly introduced in this PR.

2021-09-16 09:13 UTC, TooManyMoths commented on Assets/Scripts/Actor/ActorData.cs
>      [field: SerializeField, Tooltip("Name displayed when referring to this actor or when they are speaking.")]
Removed as its intended functionality did not work it is and no longer used.

2021-09-16 09:13 UTC, TooManyMoths commented on Assets/Scripts/Evidence/Evidence.cs
>  using UnityEngine;
Removed

2021-09-16 09:14 UTC, TooManyMoths commented on Assets/Scripts/Evidence/EvidenceController.cs
>  using System.Collections.Generic;
Will leave them to avoid changing too much of a file that isn't explicitly introduced in this PR.

2021-09-16 09:14 UTC, TooManyMoths commented on Assets/Scripts/ObjectDictionary/ObjectInventory.cs
> +using System.Collections;
Removed

2021-09-16 11:46 UTC, lyndsiWilliams submitted a review, later dismissed
Found just one thing! It looks like you've got some failing tests as well, but otherwise this looks great!

2021-09-16 11:46 UTC, lyndsiWilliams commented on Assets/Scripts/Actor/ActorData.cs
> +    private string GenerateNameWithAge()
This method is missing a summary ✨

2021-09-16 13:24 UTC, JuiceGrape commented on Assets/Scripts/ObjectDictionary/ObjectDictionary.cs
> +    private bool IsObjectInDictionary(string objectName, Dictionary<string, T> dictionaryToCheck)
Static methods are fine in OOP if you have a reason for making them. In this case, making this method static is a good idea if we want to use it in other classes as well, to avoid duplicate code. If we don't, leave it as is

2021-09-16 13:33 UTC, TooManyMoths commented on Assets/Scripts/Actor/ActorData.cs
> +    private string GenerateNameWithAge()
Added

2021-09-16 14:46 UTC, TooManyMoths commented on Assets/Scripts/ObjectDictionary/ObjectDictionary.cs
> +    private bool IsObjectInDictionary(string objectName, Dictionary<string, T> dictionaryToCheck)
Made IsObjectInDictionary and EnumerableToDictionary methods static as their output is always the same if the input doesn't change.

2021-09-16 20:47 UTC, JuiceGrape submitted a review, later dismissed

2021-09-17 17:19 UTC, JuiceGrape approved these changes
Solved bug looks good, ready to merge!

2021-09-17 23:10 UTC, lyndsiWilliams approved these changes
Looks great! ✨

2021-09-18 21:09 UTC, merged