Create issue templates
Studio-Lovelies/GG-JointJustice-Unity pull request #6
Opened 2021-08-08 15:07 UTC by notexplosive

I did this through the GitHub GUI

2021-08-08 19:52 UTC, JuiceGrape commented
Why is the the bug report in there twice?

2021-08-08 19:53 UTC, JuiceGrape requested changes

2021-08-08 19:53 UTC, JuiceGrape commented on .github/ISSUE_TEMPLATE/bug_report.md
> +...
Why is this in here twice? How even?

2021-08-08 19:54 UTC, JuiceGrape commented on .github/ISSUE_TEMPLATE/bug_report.md
> +...
Ah _ vs -, do we need both? If so, why?

2021-08-09 14:39 UTC, notexplosive commented on .github/ISSUE_TEMPLATE/bug_report.md
> +...
I made this in the GitHub GUI, I'm not sure why it duplicated the bug report template. I'll delete one and see what happens.

2021-08-09 18:05 UTC, JuiceGrape approved these changes

2021-08-09 18:40 UTC, TooManyMoths commented on .github/ISSUE_TEMPLATE/bug-report.md
> +title: "[BUG]"
Double quotes is inconsistent with single quotes used for assignees, and title in feature-request.md.

2021-08-09 18:40 UTC, TooManyMoths commented on .github/ISSUE_TEMPLATE/feature-request.md
> +## Description ##
\## is inconsistent with ** used in bug-report.md

2021-08-09 22:25 UTC, JuiceGrape commented
Could we maybe add a programmer task to the templates as well? Would really help with organizing the agile board (seeing as the feature requests are basically user stories)

2021-08-09 23:55 UTC, notexplosive commented on .github/ISSUE_TEMPLATE/feature-request.md
> +## Description ##
will fix but FWIW these came straight from the template. It's GitHub who's inconsistent not me!

2021-08-09 23:56 UTC, notexplosive commented on .github/ISSUE_TEMPLATE/bug-report.md
> +title: "[BUG]"
I made this in the GitHub GUI, (which is to say: GitHub generated this)... I'll replace with single quotes but it might break. It also might not and the GitHub provided templates are just bad.

2021-08-10 10:19 UTC, TooManyMoths approved these changes

2021-08-10 10:20 UTC, merged