Feature/70 story handler
Studio-Lovelies/GG-JointJustice-Unity pull request #82
Opened 2021-09-25 19:37 UTC by JuiceGrape

## Summary
Stories are now handled by the story handler, which can transition between different inky dialogue scripts

## Testing instructions
Check out the inky test scene

## Additional information

- `[ ]` Changes UI
- `[x]` Introduces new feature
- `[ ]` Removes existing feature
- `[ ]` Has associated resource: 
  
closes #70

2021-09-25 23:31 UTC, TooManyMoths approved these changes, later dismissed
Looks good and functions properly. Found a bug where you can loads lots of scenes at once, but technically its an oversight from one of my PRs as opposed to a fault with this PR, so approving.

2021-09-25 23:31 UTC, PhoebeMitchell commented on Assets/Scripts/TextDecoder/StoryController.cs
> +    [SerializeField] private List<Dialogue> _dialogueList;
Nit: Add tooltip

2021-09-25 23:31 UTC, PhoebeMitchell commented on Assets/Scripts/TextDecoder/StoryController.cs
> +    [SerializeField] private UnityEvent<Dialogue> _onNextDialogueScript;
Nit: Add tooltip

2021-09-25 23:31 UTC, PhoebeMitchell commented on Assets/Scripts/TextDecoder/StoryController.cs
> +        _sceneLoader = GetComponent<SceneLoader>();
Nit: Component getting should be done on awake to avoid potential script execution order issues.

2021-09-25 23:31 UTC, TooManyMoths commented on Assets/Scripts/TextDecoder/StoryController.cs
> +
Nit: Put private field together, without space.

2021-09-25 23:31 UTC, TooManyMoths commented on Assets/Scripts/TextDecoder/StoryController.cs
> +        DialogueScript = script;
Nit: Rename to narrativeScript

2021-09-25 23:33 UTC, TooManyMoths commented on Assets/Scripts/SceneLoading/SceneLoader.cs
> +        Busy = true;
This needs to be moved to the beginning of the Transition method, and potentially it should be checked in the ChangeSceneBy methods (instead of StoryController) as its possible to spam enter on the main menu and spam x in the inky test scene (when using a fade to image transition) to start loading lots of scenes.

2021-09-26 20:01 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/StoryController.cs
> +    [SerializeField] private UnityEvent<Dialogue> _onNextDialogueScript;
Turns out tooltips on events don't actually do anything on events

2021-09-26 20:35 UTC, JuiceGrape commented on Assets/Scripts/SceneLoading/SceneLoader.cs
> +        Busy = true;
Oh I totally forgot I was fixing this! I'll do it properly

2021-09-28 16:24 UTC, ViMaSter requested changes
This looks solid! Features that are getting rid of `TODO`/placeholder code are always great to see!

That said, [I don't agree with introducing arbitrary timeouts to the tests](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/pull/82#discussion_r717702127). From my point of view, they don't introduce stability and are probably a symptom of a deeper issue. I've added a suggestion on how I would go about it and it would be great if we could find a stable way around adding 14 seconds of idle time (which is around 50% of my average local run-time for all) to the tests.

2021-09-28 16:24 UTC, ViMaSter commented on Assets/Scripts/TextDecoder/StoryController.cs
> +using UnityEngine.Events;
Nit: `using System.Collections;` seems to be no longer required after these changes.

2021-09-28 16:24 UTC, ViMaSter commented on Assets/Scripts/TextDecoder/StoryController.cs
>      void Start()
Nit: Missing explicit (`private`) visibility modifier.

2021-09-28 16:24 UTC, ViMaSter commented on Assets/Scripts/TextDecoder/StoryController.cs
> +    public DialogueControllerMode ScriptType;
Nit: Current Code Style requires all member variables to be `_lowerCamelCase` (i.e. `_dialogueScript`, `_scriptType`).

2021-09-28 16:24 UTC, ViMaSter commented on Assets/Tests/PlayModeTests/Scripts/EvidenceMenu/EvidenceMenuKeyboardTests.cs
> +            yield return new WaitForSeconds(2);
I personally think that adding arbitrary delays to tests (especially all cases) is not a good practice. Is there an underlying reason for this change?

Wild guess: If you're waiting for an object a reach a certain state, I'd suggest adding logic to explicitly wait for that state, as a simple delay doesn't guarantee that your system under test actually reaches the desired state under different conditions (i.e. on a slower machine) and the test can end up failing for the exact same reason.

If that's the case, my suggestion would be to add a static method to the `Tests.PlayModeTests.Tools.InputTestTools` which takes a function (that evaluates to a boolean) and timeout as parameters and returns an `IEnumerator` that can be yielded. It waits for either `X` seconds to pass (and fails the test) or continues operation as soon as the condition is satisfied.  
The timeout can be set fairly firm and loosened, if it ends up resolving the issue. If it doesn't. there's clear information available on what expected condition is not fulfilled.

Something along the lines of:
```cs
public static IEnumerator WaitForState(Func<bool> hasReachedState, double timeoutInSeconds)
{
    DateTime timeoutAt = DateTime.Now.AddSeconds(timeoutInSeconds); // we cannot rely on UnityEngine.Time inside tests
    while (DateTime.Now < timeoutAt)
    {
        yield return null;
        if (hasReachedState())
        {
            break;
        }
    }
    Assert.Fail($"Waiting for an expected state timed out (took longer than {timeoutInSeconds} seconds){Environment.NewLine}If increasing the timeout does not resolve this and the associated expression worked before making any changes to this project, a precondition required for this test has changed and needs to be updated accordingly");
}
```
which then could be used using `yield return WaitForState(() => readyWhenIsFour == 4, 5);` )where `readyWhenIsFour == 4` would be whatever expression needs to be true for the tests to execute reliably) to replace the timeout.

2021-09-28 16:24 UTC, ViMaSter commented on Assets/Scripts/SceneLoading/SceneLoader.cs
>      /// <param name="menuNavigator">The menu navigator used to call this method. It is passed in case it needs to be disabled</param>
Nit: Pointing it out, as the contents of this method changed; this parameter comment appears to be superfluous.

2021-09-28 16:24 UTC, ViMaSter commented on Assets/Scripts/SceneLoading/SceneLoader.cs
>      /// <param name="menuNavigator">The menu navigator used to call this method. It is passed in case it needs to be disabled</param>
Nit: Pointing it out, as the contents of this method changed; this parameter comment appears to be superfluous.

2021-09-28 16:24 UTC, ViMaSter commented on Assets/Scripts/SceneLoading/SceneLoader.cs
> +        _sceneLoadOperation = SceneManager.LoadSceneAsync(_sceneIndex, LoadSceneMode.Single);
Nit: It appears this method (and thereby `_sceneIndex` too) is unused (unless it's part of an Animation-script). Rather than updating it, I would suggest deleting it until it's actually required.

2021-09-28 16:24 UTC, ViMaSter commented on Assets/Scripts/SceneLoading/SceneLoader.cs
> +        Busy = true;
Note: Unless it's part of an Animation somewhere, this property is also never set back to `false`.

2021-09-28 16:24 UTC, ViMaSter commented on Assets/Scripts/TextDecoder/DialogueController.cs
> +    private TextAsset _narrativeScript;
Nit: This field is unused now and should be safe to delete.

2021-09-28 19:37 UTC, JuiceGrape commented on Assets/Tests/PlayModeTests/Scripts/EvidenceMenu/EvidenceMenuKeyboardTests.cs
> +            yield return new WaitForSeconds(2);
@TooManyMoths this was your doing, please check this out :)

2021-09-28 21:03 UTC, TooManyMoths commented on Assets/Tests/PlayModeTests/Scripts/EvidenceMenu/EvidenceMenuKeyboardTests.cs
> +            yield return new WaitForSeconds(2);
This was added to wait for the first line of dialogue to finish playing so the menu could be opened. Possible changes could be waiting using AppearingTextController's OnDialogueEnd event, or waiting for the DialogueController's busy property to be false.

2021-09-28 21:07 UTC, TooManyMoths commented on Assets/Scripts/SceneLoading/SceneLoader.cs
> +        Busy = true;
Assuming this method always leads to a scene load (maybe not if there is an error?), it will be false in the instance of this class in the next scene.

2021-09-28 21:18 UTC, TooManyMoths commented on Assets/Scripts/TextDecoder/StoryController.cs
> +    public DialogueControllerMode ScriptType;
I think we never accounted for using public fields in the code style doc, assuming we'd always use properties with PascalCase. On that note should these be properties?

2021-10-02 11:05 UTC, JuiceGrape commented on Assets/Tests/PlayModeTests/Scripts/EvidenceMenu/EvidenceMenuKeyboardTests.cs
> +            yield return new WaitForSeconds(2);
I'll let you guys fight this one out and open a new pr when the time comes. For now, it's functional

2021-10-02 11:15 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/StoryController.cs
> +
I'll only do this if I mean to group them, and in this case I didn't want to group them

2021-10-02 11:16 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/StoryController.cs
> +        DialogueScript = script;
I think DialogueScript works well enough

2021-10-02 11:24 UTC, JuiceGrape commented on Assets/Scripts/SceneLoading/SceneLoader.cs
> +        Busy = true;
Fixed it

2021-10-02 11:27 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/StoryController.cs
> +    public DialogueControllerMode ScriptType;
As it's a struct purely for data storing purposes, it's mostly important how any instance of this is handled, as opposed to the struct itself. Seeing as they are public variables, I handled them as we have handled public variables (or properties) so far.

2021-10-02 11:28 UTC, JuiceGrape commented on Assets/Scripts/SceneLoading/SceneLoader.cs
> +        _sceneLoadOperation = SceneManager.LoadSceneAsync(_sceneIndex, LoadSceneMode.Single);
For now. I'd rather keep this as it's logical functionality to have in a class like this

2021-10-02 20:59 UTC, TooManyMoths submitted a review, later dismissed
Looks good and functional. I made a quick commit to fix the tests.

2021-10-03 00:12 UTC, ViMaSter commented on Assets/Tests/PlayModeTests/Scripts/EvidenceMenu/EvidenceMenuKeyboardTests.cs
> +            yield return new WaitForSeconds(2);
Just had a quick chat with Moths on it and we're not disagreeing; we're both in agreement actually! Moths simply offered guidance on the exact state change to wait for inside the new method I proposed and we would like that to be integrated.

The reason for the test failing here, is that the `AppearingTextController` is still animating the text box, not that 2 seconds less have passed (which is only a side effect on lower-end machines), so this is what we should be asserting inside the tests.

Also please don't resolve conversations of other people. Especially when they are explicitly marked as a required change.  
The concept of reviews inside PRs is to make sure things aren't just functional, but adhere to a technical design we all agree on and understand. Proposed alternative code is always up for debate, but the current implementation is something I can not approve: Arbitrary timeouts are a sign of flakey test, which are worse than not having them at all and will result to them being abandoned in the long run, if they don't provide a clear value. Tests are implemented to add stability and allow clear pinpointing of misbehavior.

2021-10-03 00:16 UTC, ViMaSter commented on Assets/Scripts/SceneLoading/SceneLoader.cs
> +        _sceneLoadOperation = SceneManager.LoadSceneAsync(_sceneIndex, LoadSceneMode.Single);
Gonna put this up for debate on Discord. In my mind, app-specific code that isn't run, should generally be removed. (The only exception being a library, where its entire purpose is presenting a set of logic while not being opinionated; even then however, methods should be covered with tests and thereby are used at least once.)  
For people using less sophisticated IDEs and/or trying to familiarize themselves with a new section of code, only having code that reflects current use cases is easier to understand too.

That said, this is nothing worth blocking for me.

2021-10-03 00:18 UTC, ViMaSter requested changes
The [test changes](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/pull/82#discussion_r720745487) are not implemented; making changes only to game logic is fine, but removing tests or changing their level of stability to me is not, as we've agreed on creating these tests for a reason.

2021-10-04 22:07 UTC, JuiceGrape commented on Assets/Tests/PlayModeTests/Scripts/EvidenceMenu/EvidenceMenuKeyboardTests.cs
> +            yield return new WaitForSeconds(2);
Added these changes, please make sure they're okay :)
Feel free to resolve this convo / merge if everything is a-o-fine.

2021-10-07 18:43 UTC, lyndsiWilliams approved these changes
Code looks great, just one nit. I pulled down your branch locally and played around with it, it works great! Nice job on this 😁

2021-10-07 18:43 UTC, lyndsiWilliams commented on Assets/Scripts/TextDecoder/StoryController.cs
> +    public Dialogue(TextAsset script, DialogueControllerMode type)
This method is missing a summary 🎃

2021-10-07 19:17 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/StoryController.cs
> +    public Dialogue(TextAsset script, DialogueControllerMode type)
It's a pretty default constructor in a struct. We can probably leave it un-summarized?

2021-10-07 21:30 UTC, lyndsiWilliams commented on Assets/Scripts/TextDecoder/StoryController.cs
> +    public Dialogue(TextAsset script, DialogueControllerMode type)
I'd like a summary just to be sure, I'd rather have an explicit definition instead of assuming/having to read through code to find out.

2021-10-08 17:41 UTC, JuiceGrape commented on Assets/Scripts/TextDecoder/StoryController.cs
> +    public Dialogue(TextAsset script, DialogueControllerMode type)
Oki, will do :)

2021-10-08 22:33 UTC, closed without merging